### ISSUE TITLE
HOW TO: Import custom JavaScript file/library?

### ISSUE THREAD

**Issue by veslorens** [centrual/cordova-template-framework7-vue-webpack#10]
Could you please help me on how to and where to import custom JavaScript file and/or library or from a CDN?
Because usually I just inject it at the bottom part of the `<body>`, but it seems that this has a different method. Thank you so much.

**Comment by centrual** [comment]
Hello @veslorens 

Node js has not a way to load url in `require` method.

You have three way to do this:
- Check is there a package in npmjs first. If there is an npm package you can install it with `npm install` command. You can do it yourself with fork repo and add package.json file if there is github page but it haven't package.json.
- Download required files (with all dependencies) from cdn and load from local.
- Async load from url: http://stackoverflow.com/questions/7809397/how-to-require-from-url-in-node-js

Have a great day!

**Comment by veslorens** [comment]
Hi @centrual

I'll try these methods you mentioned. 
Thank you so much for your help.

Cheers!
