### ISSUE TITLE
Question about webpack

### ISSUE THREAD

**Issue by tribalboy3000** [centrual/cordova-template-framework7-vue-webpack#100]
I have everything working correctly. Since this is my first time working with webpack I'm curious if that is setup correctly? When I inspect I can't find the line the style is on, all I see is this:

![image](https://user-images.githubusercontent.com/2553727/37088229-e1bad74e-21b9-11e8-9e0a-3b1e6cc413f8.png)

Is there someway I can update the settings to make it easier to inspect?

Also, thanks for putting this template together.

**Comment by caiobiodere** [comment]
hey @tribalboy3000 That's how css-loader, sass-loader works you can see more about that creating or doing small examples

* [Small example using css-loader](https://css-tricks.com/css-modules-part-2-getting-started/#article-header-id-3)
* [Explanation about css-loader](https://medium.com/a-beginners-guide-for-webpack-2/webpack-loaders-css-and-sass-2cc0079b5b3a)
