### ISSUE TITLE
lodash/lodash.js" as it exceeds the max of "500KB".

### ISSUE THREAD

**Issue by edoofx** [centrual/cordova-template-framework7-vue-webpack#101]
cordova : 8.0.0
android  : 7.0.0
node : 8.9.4
npm : 5.6.0

trying to downgrade cordova to 6.5.0 . same.

```
Error: Error happened when webpack build: Error: Command failed: "C:\apps\v2test\node_modules\.bin\webpack.cmd"
[BABEL] Note: The code generator has deoptimised the styling of "C:/apps/v2test/node_modules/lodash/lodash.js" as it exceeds the max of "500KB".
[BABEL] Note: The code generator has deoptimised the styling of "C:/apps/v2test/node_modules/framework7/dist/framework7.esm.bundle.js" as it exceeds the max of "500KB".
```

**Comment by caiobiodere** [comment]
please check using this issue https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/issues/55

**Comment by edoofx** [comment]
i guess different problem..

im trying with ur refference . same.

delete file package lock . 
run npm install .
cordova run android .

getting 
```
Error: Error happened when webpack build: Error: Command failed: "C:\apps\v2test\node_modules\.bin\webpack.cmd"
[BABEL] Note: The code generator has deoptimised the styling of "C:/apps/v2test/node_modules/lodash/lodash.js" as it exceeds the max of "500KB".
[BABEL] Note: The code generator has deoptimised the styling of "C:/apps/v2test/node_modules/framework7/dist/framework7.esm.bundle.js" as it exceeds the max of "500KB".
```

**Comment by teddyhendryanto** [comment]
hi @caiobiodere , @edoofx 

sorry for jump in.
I got stuck for 3 hours in same error when execute cordova run browser on my windows10 x64.

Error: Error happened when webpack build: Error: Command failed: "C:\wamp\www\com.example.text\node_modules\.bin\webpack.cmd"
[BABEL] Note: The code generator has deoptimised the styling of "C:/wamp/www/com.example.text/node_modules/lodash/lodash.js" as it exceeds the max of "500KB".
[BABEL] Note: The code generator has deoptimised the styling of "C:/wamp/www/com.example.text/node_modules/framework7/dist/framework7.esm.bundle.js" as it exceeds the max of "500KB".

I've tested run in Linux Ubuntu 17.10 and it is running well.

My current version
cordova : 8.0.0
android : 7.0.0
node : 8.9.4
npm : 5.6.0

Need your advice.
Thank you

**Comment by inallweather** [comment]
i have add exclude on vue-loader in webpack.config.js

**Comment by inallweather** [comment]
i have added  'exclude: /node_modules/ '  [test: /\.vue$/,**exclude: /node_modules/**, loader: 'vue-loader'] in webpack.config.js
 My current version
cordova 8.0.0 android 7.0
node  8.10
OS: win10 x64

**Comment by teddyhendryanto** [comment]
@inallweather thank you for your response. 
sorry i'm not good enough in webpack.
can you show me, which part should I add in webpack.config.js?
thank you..

**Comment by inallweather** [comment]
![image](https://user-images.githubusercontent.com/13284416/37436446-f6586d28-2822-11e8-8851-102c5e10565a.png)

**Comment by inallweather** [comment]
![image](https://user-images.githubusercontent.com/13284416/37436545-6d61f308-2823-11e8-918b-c587ec1c7930.png)

would your see in the red shape

**Comment by inallweather** [comment]
in the wepack.config.js file, do you look for the module:{ rules:[ {test: /\.vue$/, exclude: /node_modules/, loader: 'vue-loader',** options: {loaders: {js: {loader: 'babel-loader', options: {presets: ['env'], plugins: ['transform-object-rest-spread']}}}}}]}

**Comment by caiobiodere** [comment]
@inallweather I made your tips :) Hey @teddyhendryanto could you change your webpack config file using this?

From ->
`{test: /\.vue$/, loader: 'vue-loader', options: {loaders: {js: {loader: 'babel-loader', options: {presets: ['env'], plugins: ['transform-object-rest-spread']}}}}},
{test: /\.js$/, exclude: /node_modules\/(?!(framework7|framework7-vue|template7|dom7)\/).*/, use: {loader: 'babel-loader', options: {presets: ['env'], plugins: [ 'transform-runtime', 'transform-object-rest-spread' ]}}}`

To ->
`{test: /\.vue$/, exclude: /node_modules/, loader: 'vue-loader', options: {loaders: {js: {loader: 'babel-loader', options: {presets: ['env'], plugins: ['transform-object-rest-spread']}}}}},
{test: /\.js$/, exclude: /node_modules(\/|\\)(?!(framework7|framework7-vue|template7|dom7)(\/|\\)).*/, use: {loader: 'babel-loader', options: {presets: ['env'], plugins: [ 'transform-runtime', 'transform-object-rest-spread' ]}}}`

**Comment by inallweather** [comment]
yes

**Comment by edoofx** [comment]
like @teddyhendryanto says .. im using ubuntu for now , and no one problem , even with fresh clone like im doing before.. 
but on windows . error error error and error ..

@caiobiodere  thanks in advance..

**Comment by teddyhendryanto** [comment]
@caiobiodere woww. after changing webpack config with your code, it works fine now!!
now I can start develop with your template using windows.
Thank you.. :)

**Comment by caiobiodere** [comment]
Great work! :)
