### ISSUE TITLE
How do we switch out framework 7 with other frameworks like quasar or onsenui?

### ISSUE THREAD

**Issue by rlam3** [centrual/cordova-template-framework7-vue-webpack#104]
How do we switch out framework 7 with other frameworks like quasar or onsenui?

Another Question. If I wanted to add a cordova plugin, how do I import/integrate it? Thanks!

**Comment by caiobiodere** [comment]
To import/integrate more cordova plugins you just need to follow this way in your project folder:
```cordova plugin add cordova-plugin-geolocation```
