### ISSUE TITLE
hey did you test this template on your real phone

### ISSUE THREAD

**Issue by nuxcasino** [centrual/cordova-template-framework7-vue-webpack#107]
Sorry for that. I have almost 5 days work on this template. every think working well. but when I deploy my  real phone its first showing   Waiting for device ready.... 

I'm not good coder, but I think something wrong there. 

thanks advance

**Comment by caiobiodere** [comment]
What kind of phone are you using there?
Please send to us more information about that

**Comment by nuxcasino** [comment]
Sorry, it was same mistake on my code. now its working.  but  when I first time run cordova.js loaded after than cordova.js not found
