### ISSUE TITLE
Android   ：Uncaught ReferenceError: Camera is not defined

### ISSUE THREAD

**Issue by xiyanglove** [centrual/cordova-template-framework7-vue-webpack#109]
Ios can call Cordova plugin，Android ：“Uncaught ReferenceError: Camera is not defined”，Any plugin fails to call

**Comment by caiotarifa** [comment]
``` bash
$ cordova plugin add cordova-plugin-camera
```

**Comment by caiobiodere** [comment]
I think you need to check if your plugin has been installed on Android, to do that just remove and create platform again:
```
cordova platform rm android
cordova platform add android
```

**Comment by prosenjeet123** [comment]
Or may be you are calling the script before the cordova.js gets loaded
