### ISSUE TITLE
Device ready in browser mode? (Linux OS)

### ISSUE THREAD

**Issue by Grogglex** [centrual/cordova-template-framework7-vue-webpack#11]
I'm wondering if there is any way to listen for the `deviceready` call in this setup from running it in the browser or building it?

https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-device/

I can't seem to catch that event. Any experience with this?

This is more of a Cordova issue. I'll close it.

**Comment by centrual** [comment]
You can use directly with this template. It's automatically injects platform's cordova file, so you can catch `deviceready` event.

**Comment by Grogglex** [comment]
I thought maybe it was available in the browser (device.uuid) but it doesn't seem to be. It says it works for browser but I'm finding that the event is never firing. Could it have to do with the 404 on cordova.js on local live reload mode?

**Comment by centrual** [comment]
Interesting, it's working for me.

What's your OS? if it's mac os, there is a problems with it.

**Comment by Grogglex** [comment]
It's Arch Linux. Can you show me where you're listening for the event? You're running `cordova run browser`? And you're using the Cordova device plugin? I'll try to follow what you have and see if it's a Linux issue.

**Comment by centrual** [comment]
it's not working in mac os, so i think there is a problem in linux too. I am using windows. Windows working, but mac os doesn't working. I'll update the template when `extract-text-webpack-plugin` new version released.

Template adds `cordova.js` script tag to index.html automatically with cordova hook when you use command `build`
Template injects correct `cordova.js` file to page automatically when you use command `-- --live-reload`

You can find more information about that in https://github.com/centrual/cordova-template-framework7-vue-webpack/

so if it's not working in linux, please write here. I'll test it when i upgrading to new version.

Have a great day!

**Comment by centrual** [comment]
Hello @Grogglex 

I updated the template. Can you read instructions from https://github.com/centrual/cordova-template-framework7-vue-webpack/ and check one more time?

Thank you so much.
Have a great day!

**Comment by Grogglex** [comment]
The issue is on Linux I don't think we can add Ios as a platform?

**Comment by centrual** [comment]
Your problem about webpack output, not about ios. Just re-create project and copy your project files into new project and everything will work. (My english is not very good, sometimes i can write meaningless or hard cues, i'm sorry for that)

**Comment by Grogglex** [comment]
No worries! Thanks I'll try it out.

**Comment by Grogglex** [comment]
Solved by #12
