### ISSUE TITLE
How do we integrate admob?

### ISSUE THREAD

**Issue by rlam3** [centrual/cordova-template-framework7-vue-webpack#111]
How do we integrate admob?

I've been trying to integrate the following cordova plugin 
https://github.com/ratson/cordova-plugin-admob-free

Was wondering if I could get your input on how to integrate with this template. 

Thanks! @caiobiodere

**Comment by caiobiodere** [comment]
hey @rlam3 did you try using this?

```cordova plugin add cordova-plugin-admob-free --save```

**Comment by caiobiodere** [comment]
@rlam3 did you have some time to test that?

**Comment by KevinCarroll7737** [comment]
I am doing this ATM, any advises?
