### ISSUE TITLE
Windows application hangs

### ISSUE THREAD

**Issue by arsalan1248** [centrual/cordova-template-framework7-vue-webpack#113]
Hello.

On opening the application, I locked the screen on windows and re-login from the locked screen after 15-20 min, the application always hangs irrespective of screen or action the user was on the app.

Has anyone faced the screen freezing problem?

**Comment by caiobiodere** [comment]
@arsalan1248 did you try restarting your emulator device that could be a problem with your memory. Please check that

**Comment by arsalan1248** [comment]
@caiobiodere thank you for your time.
I have updated my windows machine and since then i did not observe any hanging issue in my application.

Running the following command on Powershell prints the version
[System.Environment]::OSVersion.Version

Following is output from the laptop on which application is not hanging

Major  Minor  Build  Revision
-----  -----  -----  --------
10      0      17134   0
