### ISSUE TITLE
Stacked Pages

### ISSUE THREAD

**Issue by fgarcia5** [centrual/cordova-template-framework7-vue-webpack#114]
I need the pages to be loaded into the DOM only once. I have tried setting stacked-pages in true to the main view but the screens are loaded again and again repeatly.

I also tried adding the stacked property to the pages but it did not work either.

How can I show the pages that are already loaded in the DOM?

I understand one can navigate to a page by page Name or the ref but I could not achieve.

Could someone help me with a concrete example?

Thanks in advance!

**Comment by caiobiodere** [comment]
@fgarcia5 please see this issue -> http://forum.framework7.io/t/solved-v2-0-2-how-do-i-enable-domcache-in-version-2/1659

**Comment by fgarcia5** [comment]
Hi @caiobiodere .

Many thanks for your answer.

I don't undertand how this example could help me. I tried putting "stackedPages" and "animateWithJS" to true but it didn't work.

For more information you can see the issue in Framework7 Forum: http://forum.framework7.io/t/v2-stacked-pages/3808

Any idea how to solve this?

Thank you again, regards.

**Comment by fgarcia5** [comment]
The issue was resolved.

You can see: http://forum.framework7.io/t/v2-stacked-pages/3808
