### ISSUE TITLE
Is there any plan to upgrade to framework 3.x?

### ISSUE THREAD

**Issue by wxfred** [centrual/cordova-template-framework7-vue-webpack#117]
Expecting upgrading and making it easier to change port.

**Comment by caiobiodere** [comment]
@wxfred I will check this tonight :)

**Comment by mgd722** [comment]
@caiobiodere i submitted a PR for this last night.  anything missing?

**Comment by caiobiodere** [comment]
Done guys 👍

**Comment by wxfred** [comment]
Bravo!
