### ISSUE TITLE
Including cordova plugin js file (Linux OS)

### ISSUE THREAD

**Issue by alberto-bottarini** [centrual/cordova-template-framework7-vue-webpack#12]
I'm using this cordova plugin https://github.com/jeduan/cordova-plugin-facebook4, but during a ```cordova run browser -- --live-reload``` its js file get ignored.
Everything works if I run ```cordova run browser```.

How can I tell cordova to include some other plugins using your template?

**Comment by centrual** [comment]
Hello @alberto-bottarini 

This template, copies all cordova related assets to `www/cordova_platform_files/` directory and it loads from there.

Can you check your files inside of `www/cordova_platform_files/` after `cordova run browser -- --live-reload` command? If you find which files are missing, i can update copy code with this information.

Have a great day!

**Comment by alberto-bottarini** [comment]
I think we have a problem. 
If I run ```cordova run browser -- --live-reload```, only one file gets copied in www, and this is the "standard" cordova index.html, the one that displays ```Waiting for device ready...```.

It's weird because in the browser everything works great :)

Correct files get copied only if I run ```cordova run browser```.


Thanks

**Comment by centrual** [comment]
So it's seems currently not working in linux too. If you have windows OS, can you test in windows OS too?

I'll make update when `extract-text-webpack-plugin` released. Because currently `extract-text-webpack-plugin` have big issues with webpack 2 in mac os and probably in linux too.

If there is no `cordova_platform_files` folder in `www` after run command, it means `hookers.js` not worked good.

I added warning text about this problem in readme.

Can you help me to linux os tests for next release?

Thanks for feedback 👍

**Comment by alberto-bottarini** [comment]
Yes of course. But i'm totally new to cordova so you have to tell me exactly what I have to do :)

**Comment by centrual** [comment]
Hello @alberto-bottarini 

I updated the template. Can you check instructions from https://github.com/centrual/cordova-template-framework7-vue-webpack and test template?

Thank you so much.
Have a great day!

**Comment by Grogglex** [comment]
Hi @centrual What's the simplest way to upgrade to the new template from a currently existing project? I'd like to use the `device ready` functionality in an existing project.

**Comment by Grogglex** [comment]
It seems like it's definitely to do with the hooker.js library. The diff is definitely between `run browser` and `run browser --lr`.

If I run `run browser` I get the following output:
```
Before deploy hook started...
Checking is node modules installed...
Node modules already installed.
Starting webpack build...
Webpack build completed to www folder successfully!
Cordova hook completed. Resuming to run your cordova command...
Running command: /mnt/Storage/Workspace/Colibri/platforms/browser/cordova/build
Cleaning Browser project
Dev server not running. Skipping...
Running command: /mnt/Storage/Workspace/Colibri/platforms/browser/cordova/run --nobuild
Static file server running @ http://localhost:8000/index.html
CTRL + C to shut down
```

And when I run `cordova run browser -- --lir` I get:

```
Before deploy hook started...
Checking is node modules installed...
Node modules already installed.
Project is running at http://0.0.0.0:8080/
webpack output is served from /
Content not from webpack is served from /mnt/Storage/Colibri/StrollopiaVue/www
```
Could it have something to do with:

```
sys.checkNodeModules()
    .then(() => {
        if (isBuild || ((isRun || isEmulate || isPrepare) && !isLiveReload && !isNoBuild)) {
            return sys.makeNonDevServerChanges().then(() => sys.startWebpackBuild(isRelease))
        } else if (isServe || (isRun || isEmulate) && isLiveReload) {
            return sys.makeDevServerChanges().then(() => sys.startWebpackDevServer())
        }
        else
            return sys.emptyDefer()
    })

```

**Comment by centrual** [comment]
I updated the library currently, can you update? (you need to create new project with `cordova create project_dir --template cordova-template-framework7-vue-webpack` command)

and infos are correct. It seems working good, just you need to upgrade library.

**Comment by Grogglex** [comment]
Sure. I can do that. Is there a way to update my existing project? Thanks man. Also, I'll likely be using this framework for the next while so if I find a way to improve your project I'll make a PR.

**Comment by centrual** [comment]
Currently there is no way to upgrade, but you can do it manually if you want. Overwrite this files with github files:

* template_src/hooks/beforedep.js
* template_src/hooks/hookers.js
* template_src/webpack/dev_helpers/device_router.html
* template_src/webpack.config.js
* template_src/package.json

open terminal or command line tool and change directory to your project root folder (`cd /your/project/folder`)

run `npm i && npm update` commands

**Comment by Grogglex** [comment]
Hrrm I must be missing something centrual, I've changed the files:
```
        modified:   hooks/beforedep.js
        modified:   hooks/hookers.js
        modified:   package.json
        modified:   src/index.html
        modified:   webpack.config.js
        modified:   webpack/dev_helpers/CordovaDeviceRouter.js
        modified:   webpack/dev_helpers/device_router.html
        modified:   webpack/plugins/CordovaHtmlOutputPlugin.js
```
but it doesn't seem to be using your new config.

**Comment by centrual** [comment]
did you used npm i and npm update commands?

**Comment by Grogglex** [comment]
Yeah, I got it working with your help. Thanks.

**Comment by centrual** [comment]
Thanks for feedbacks. Closing the issue.
