### ISSUE TITLE
IOS build and deploy

### ISSUE THREAD

**Issue by Bek81** [centrual/cordova-template-framework7-vue-webpack#120]
Hi,
I need help.

I installed and develop a test app. Now I should do the package and install everything on IOS devices.
I have generated various certificates and provisioning.
But now I do not know how to proceed using the cordova commands (without Xcode).

Can you help me? 
Can you tell me a step by step procedure to deploy on device?
Please.

Thanks and regards.

**Comment by caiobiodere** [comment]
Please check this link:
https://code.tutsplus.com/tutorials/how-to-submit-an-ios-app-to-the-app-store--mobile-16812

**Comment by Bek81** [comment]
Oh... ok. Thanks a lot,
but I do not have an xcode project: I installed everything following your instructions with the command
"cordova create <project_create_dir> [com.example.projectname] [ProjectClassName] --template cordova-template-framework7-vue-webpack".

is it ok anyway?

Also, I don't want to upload the app to the app store.

**Comment by Bek81** [comment]
Ok,
after several attempts, and after finding the xcodeproject file in the platforms folder, I managed to build ipa with xcode and I installed everything on ipad. it works!

**Comment by caiobiodere** [comment]
Awesome work @Bek81 !
