### ISSUE TITLE
Live Reload on IOS emulator

### ISSUE THREAD

**Issue by Bek81** [centrual/cordova-template-framework7-vue-webpack#121]
Hi,
some problems with **live-reload** on my iphone simulator:

I follow your
[https://github.com/caiobiodere/cordova-template-framework7-vue-webpack#warning-for-linux-and-mac-os-users](url)

> WARNING (For Linux and Mac OS users):
For live-reload i can't find easy way to do fixed version of this. But you can develop your app with this way: cordova platform add ios browser (browser needs for development in live-reload mode.)
cordova run ios -- --lr (wait till app opens in your ios emulator or phone. it will close console output after publish, so live-reload will not work. don't close the app and go to next step.)
cordova run browser -- --lr (you can use live-reload in your phone-emulator and browser at same time. you can edit your files in live-reload mode now.)

but when I start "cordova run browser - --lr" obviously the answer is as follows:
"Error: listen EADDRINUSE 0.0.0.0:8081".

Can you help me please. I would need the live reload also in the emulator.

Thanks and regards.

**Comment by Bek81** [comment]
I tried this way:

1. phonegap run ios -- --lr
2. cordova run browser -- --lr

it seems to work.

**Comment by caiobiodere** [comment]
This is probably because you already had one listener with 8081 on your list like they said to you (EADDRINUSE).

You could use this guide when that happens:

1. (Find out the process ID (PID) which is occupying the port number (e.g., 8081) you would like to free)
sudo lsof -i :8081

2. Kill the process which is currently using the port using its PID
sudo kill -9 PID

**Comment by reksc** [comment]
Hi, I'm experiencing pretty much the same issue. I understand the nature of the error etc.

In my case, every call to ``cordova run`` will setup a dev server listening on :8081. However, the command exits after running the selected environment (is this normal?) and the only option I can think of to stop the server process is the one listed above - killing through it's PID. When working on npm/webpack projects it is rather common to have a live process bound to cli after running ``npm run dev`` that you can terminate through e.g. ``ctrl + c``.
