### ISSUE TITLE
MD Icons support

### ISSUE THREAD

**Issue by khudia** [centrual/cordova-template-framework7-vue-webpack#122]
Can't fix to work material icons.
`<f7-icon material="home"></f7-icon>` = not works((
thanks!
----
and another question where to  put this
`document.addEventListener("deviceready", onDeviceReady, false);`

thanks a lot!!! your bundle is awesome!!

**Comment by caiobiodere** [comment]
I fixed to support material icons on this theme that you can check here: https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/releases/tag/2.0.8

```document.addEventListener("deviceready", onDeviceReady, false);```
You can put that code on main.js file

**Comment by khudia** [comment]
Thanks a lot!!
