### ISSUE TITLE
:push-state doesn't work

### ISSUE THREAD

**Issue by davide93** [centrual/cordova-template-framework7-vue-webpack#124]
`<f7-view url="/"  :push-state="true" :main="true"></f7-view>`

or via

```
            f7params: {
                theme,
                routes,
                id: 'io.framework7.testapp',
                view: {
                    pushState: true
                }
            }
```

Work correctly only via live reload browser/android. But not in compiled app.
Can you confirm? Any suggestions?

Ty.

**Comment by caiobiodere** [comment]
@davide93 Please check framework7 v3 documentation on Push State section

https://framework7.io/docs/view.html

**Comment by caiobiodere** [comment]
@davide93 How was it?

**Comment by davide93** [comment]
@caiobiodere  Add :push-state directly in <f7-view :push-state="true"> it doesn't work.

**Comment by wxfred** [comment]
@davide93 Accroding to the author of framework7, you can try to listen 'backbutton' instead of using 'push-state'. It seems that push-state is unstable with Cordova app.
[Check this out](http://forum.framework7.io/t/cordova-phonegap-build-white-page-now/1420/17)

**Comment by caiobiodere** [comment]
Thank you @wxfred
