### ISSUE TITLE
STATIC FOLDER - files content

### ISSUE THREAD

**Issue by Bek81** [centrual/cordova-template-framework7-vue-webpack#125]
Hi,
I tried to insert a sub directory called "experience" in the "src/static" folder. Its structure is like in the screenshot:
<img width="168" alt="screen shot 2018-08-20 at 11 08 33" src="https://user-images.githubusercontent.com/10144127/44331284-74a08b80-a469-11e8-9c5b-c0b6aa7a9793.png">

I run with the command:
`cordova run browser -- --lr`

When I try to modify one of the static files (index.html, css/default.css, js/default.js), the contents of the modified file are completely deleted.

How can I solve the issue?
Do I have to change the configuration of the "webpack.config.js" file? How?

Thanks and regards.

Benedetto

**Comment by Bek81** [comment]
Please, can you help me?

**Comment by caiobiodere** [comment]
Hi @Bek81 I will try this tonight

**Comment by Bek81** [comment]
Hi @caiobiodere ,
do you have any news for us?

**Comment by caiobiodere** [comment]
Hi @Bek81 I fixed your problem check using this release: 

https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/releases/tag/2.0.9

**Comment by Bek81** [comment]
Hi @caiobiodere ,
I have updated (according to the release) the file "hooks/hookers.js"; I don't think there was anything else to update.
Now almost everything seems to work; there is only one thing that seems wrong to me:
I add the line of code
`console.log('fix test');`
to the file "src/static/experience/js/default.js".
The contents of the file are not deleted.
The contents are correctly copied to the file in the "www" folder (root).
The file is **not** updated in the "www/static" subfolder of the "platforms/browser.

Should not everything happen automatically?

Thanks

**Comment by caiobiodere** [comment]
Hi, @Bek81 for running with live-reload you just need to have those files in the root folder.

**Comment by Bek81** [comment]
Yes, ok.
So when I build, the static folder is copied to the platform. right?

**Comment by caiobiodere** [comment]
Yes, correctly

**Comment by Bek81** [comment]
Thanks a lot!
