### ISSUE TITLE
cordova run ios error (domain=NSPOSIXErrorDomain, code=2)

### ISSUE THREAD

**Issue by mwargan** [centrual/cordova-template-framework7-vue-webpack#126]
On a fresh install I'm able to get cordova running in the browser, but when I run `cordova run ios` I get the following error:

```
** BUILD SUCCEEDED **

Copying platform cordova files...
All platform files copied to www/platform_cordova_files/ directory!
No target specified for emulator. Deploying to iPhone-X, 11.4 simulator
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
```
Running Cordova 8 on MacOS Mojave.

What is going on here?

**Comment by caiobiodere** [comment]
I didn't test yet but why are you try running on MacOS Mojave? I think that should be your problem try updating your system and Xcode versions.

**Comment by mwargan** [comment]
System is running the latest Beta of MacOS - can't update further :D!

I got this to work but can't remember what it was - I think something to do with the provisioning profile...

Later on I did have to get Xcode Version 10.0 beta 6 to overcome an issue with device support for iOS12 beta version - for anyone working with the Apple beta program ;)!

**Comment by caiobiodere** [comment]
Well done! Probably because you didn't correctly set your account profile and certificates, profiles etc

Let me know anything else.
