### ISSUE TITLE
https for map api usage at debuging

### ISSUE THREAD

**Issue by khudia** [centrual/cordova-template-framework7-vue-webpack#127]
is it possible to use https protocol for server while debuging to use, in my case, yandex map api.

**Comment by caiobiodere** [comment]
hey @khudia I think you can use these guides:

https://cordova.apache.org/docs/en/latest/guide/appdev/security/
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/

**Comment by khudia** [comment]
think i won't fix it out (
