### ISSUE TITLE
assets/images

### ISSUE THREAD

**Issue by Bek81** [centrual/cordova-template-framework7-vue-webpack#128]
Hi,
I have a problem with image loading.

I'm using the Vuex.Store object in storage.js where I instantiate an element with the path "assets/images/test.jpg" (I tried different options for the path) called in a VUE file.
The file is certainly in the "src/assets/images/" folder, but I have a 404 error in the browser console (screenshot).

<img width="147" alt="screen shot 2018-08-31 at 15 17 12" src="https://user-images.githubusercontent.com/10144127/44914684-422c4380-ad31-11e8-8736-ffc69b4fd5c8.png">
<img width="482" alt="screen shot 2018-08-31 at 15 18 43" src="https://user-images.githubusercontent.com/10144127/44914686-422c4380-ad31-11e8-95ff-66ea54bb6321.png">

Do I have to import every images into the storage.js file? e.g.:
```
import myImg from "assets/images/test.jpg"
...
...
thumb: myImg
```

What's the best way?

Can you help me please?

Thanks and regards.

**Comment by caiobiodere** [comment]
@Bek81 please check:

https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/issues/17

**Comment by Bek81** [comment]
Hi @caiobiodere  ,
so I have to use the "src/static" folder instead of "src/assets/images"?

**Comment by caiobiodere** [comment]
you can use both ways if you are trying on assets try like this:

`<img src="../../images/logo.png" width="189" height="144" alt="">`
because webpack creates another name for images and everything that's why you need to put the correct reference like "../../images/logo.png" to find them

**Comment by caiobiodere** [comment]
hey @Bek81 how was it?

**Comment by Bek81** [comment]
Ok, @caiobiodere .
for now we will use the static folder. thank you

**Comment by caiobiodere** [comment]
awesome!

**Comment by mingxin-yang** [comment]
@caiobiodere Hi,i have the same problem.
I have put the images into static/image/ folder.
> assets/vue/pages/main.vue
```
<f7-icon slot="media" icon="icon-f7"></f7-icon>
```
> assets/sass/main.scss
```
  .icon-f7 {
	background: url(./static/image/f7-icon.png) no-repeat center;
	background-size: cover;
  }
```

**Comment by itsyub** [comment]
@mingxin-yang , try using `background: url(static/images/f7-icon.png)`

**Comment by mingxin-yang** [comment]
@itsyub ，I try it ,but it didn't work.
but,
```
<div class="help-img">
     <img src="static/image/ic_drawer_help.png" height="30px" width="30px">
</div>
```
this is success.
I think that it is the error of  "f7-icon"
