### ISSUE TITLE
Build for ios

### ISSUE THREAD

**Issue by khudia** [centrual/cordova-template-framework7-vue-webpack#129]
When i am tryin to build app using xcode on debuging device, it's building with live reload, but i don't need. I need of course in testing but i don't know how to disable or enable it later. May there is some command to just build app without hooks so that i will be able to build app on my debug device just using xcode and then publish.

**Comment by khudia** [comment]
`cordova prepare ios` )) thanks
And i do not understand is there is an ability for livereload using real ios device

**Comment by caiobiodere** [comment]
@khudia yes of course, you just have to do it by yourself using (please check if your iPhone has been connected and profiles, account, etc are okay): 
```cordova run ios -- --lr ```

**Comment by khudia** [comment]
All is done. Thanks. And my app is published at appstore successfully....after two weeks of pending))
