### ISSUE TITLE
Need help: white screen on adobe phonegap build

### ISSUE THREAD

**Issue by luckynum7** [centrual/cordova-template-framework7-vue-webpack#13]
## Background:

Hi, 

I purchased the apple developer program, and don't have a Mac. I need to build an app for both android and iphone.

I work in my own docker [image](https://hub.docker.com/r/timefairy/asdfsdkman/) with docker-compose ([config](https://gist.github.com/luckynum7/a00a904c914608fc2b1fa444bcfc9226)), and test the code on an android with usb plugged.

The live-reload works. It shows blank screen sometimes, but it's not annoying. One can simply press `return` on the phone, the page will reload again.

The build command also works, install the right .apk (~28 MB)
```bash
export NODE_ENV=development
phonegap analytics off
phonegap run android -d --device
```

## Issue:

However, when I use the [adobe phonegap build](https://build.phonegap.com/) to build the app, it build a much smaller .apk (~3.4 MB), and shows a white screen.

test project generated with `phonegap run android`:
```bash
├── AndroidManifest.xml
├── assets
│   └── www
│       ├── c28e4029ac8795ebc20a.main.js
│       ├── cordova.js
│       ├── cordova-js-src
│       ├── cordova_plugins.js
│       ├── i-f7-ios.png
│       ├── index.html
│       └── styles.css
├── classes.dex
├── META-INF
│   ├── CERT.RSA
│   ├── CERT.SF
│   └── MANIFEST.MF
├── res
...
│   └── xml
│       └── config.xml
└── resources.arsc
```

test project generated in phonegap service:
```bash
├── AndroidManifest.xml
├── assets
│   └── www
│       ├── assets
│       ├── cordova.js
│       ├── cordova_plugins.js
│       ├── hooks
│       ├── index.html
│       ├── main.js
│       ├── main.vue
│       ├── package.json
│       ├── phonegap.js
│       ├── routes.js
│       ├── webpack
│       ├── webpack.config.js
│       └── www
├── classes.dex
├── META-INF
│   ├── CERT.RSA
│   ├── CERT.SF
│   └── MANIFEST.MF
├── res
...
│   └── xml
│       └── config.xml
└── resources.arsc
```

## Questions:

1. Does it mean that the phonegap build service ignore the hooks?
2. I don't have a Mac right now. So I can only build the app on
    - Linux - How?
    - Windows - How?
    - Build services - Any suggestions?

Any other suggestions please?

### 1. folder structure
I thought the issue may be the folder structure. So I make a test project

my project:
```bash
├── app
│   ├── config.xml
│   ├── Dockerfile
│   ├── hooks
│   ├── node_modules
│   ├── package.json
│   ├── platforms
│   ├── plugins
│   ├── src
│   ├── webpack
│   ├── webpack.config.js
│   └── www
├── docker-compose.yml
├── gradle
│   └── wrapper
├── gradlew
├── gradlew.bat
└── README.org
```

test project:
```bash
├── config.xml
├── hooks
├── node_modules
├── package.json
├── platforms
├── plugins
├── src
├── webpack
├── webpack.config.js
└── www
```

the test project resulted an .apk with white screen, and smaller size (141 KB vs 2.1 MB) too.

**Comment by centrual** [comment]
Hello @luckynum7

You can debug your app with http://geeklearning.io/apache-cordova-and-remote-debugging-on-ios/. It will display network errors (missing files), html structure and javascript errors. This infos can be very helpful for fix the problem.

You don't need mac for build iphone apps. You can use virtual machine ( you can run mac os image in `wmware workstation` ). You can develop inside of vm. You can install linux or windows too.

Lastly problem probably about phonegap. If phonegap not working well, you can use cordova too for fast development.

**Comment by BHunter2889** [comment]
@luckynum7 I saw this was still open, so idk if it was solved, but you can build through PhoneGap Build on windows or Linux for iOS as long as you have an app key/certificate. You can get that from the Apple Developer online Dashboard by uploading your code. Also, if you did have access to XCode on a mac, you don't have to have the Dev Membership to generate a certificate for testing (that's where I'm at because I'm a poor startup dev haha!). 

Note: If I'm off on something its probably because I haven't tried using @centrual 's package yet, I just now found it and will be trying it out in the coming days. Thanks!

**Comment by centrual** [comment]
Hello @BHunter2889 

Currently it's not fixed and i didn't tested it. Also probably phonegap build services not working with this template.

Currently i strongly suggesting to use cordova with this template.

**Comment by strixy** [comment]
I'm experiencing the white screen of death using Cordova and Android emulator (v7.1.1) via Android Studio. The web dev workflow is fine, but post build I get a blank white screen. The only error I see in Logcat is `E/libEGL(5054): validate_display:99 error 3008 (EGL_BAD_DISPLAY)`

Could this be a whitelist issue? I tried editing the ./config.xml file but something is building that. Not sure from where yet. I'll try to debug it more later.

**Comment by strixy** [comment]
I built this package from scratch to try and reproduce this error, but I could not. It must be in my code somewhere. Thanks.

**Comment by FabianSilva** [comment]
I tested cordova and I have the same problem of white screen, I follow what say @beerett on https://github.com/vuetifyjs/vuetify/issues/2303 about using quasar wrapper, remove on /dist folder all starting "/" of index.html (and also from .js files) and tested again to build cordova apk and its now runs... 
also change "history" mode on route\index.js definition
mode: 'hash instead of mode: 'history' and it have to work

**Comment by FabianSilva** [comment]
to make to work the dist release and not have to edit any file on dist manually from '/static/... to 'static/... 
just edit config\index.js 

```
assetsPublicPath: '/',
```
replace to
```
assetsPublicPath: '',
```
I doesn't know how to create a new npm run build with multiple confgs (or npm build [newconfig], then I created two index.js.web and index.js.cor and two bat files that create dist folder for web and dist folder to cordova apk

bat file to build dist and generate apk to test (also generate apk that is ready to deploy to google play console):
```
rem dist folder for cordova apk
c:
cd \myproject\config
del index.js
copy index.js.cor index.js

cd \myproject
start /wait npm run build [[note: when end to build I type "exit" to continue with next line... at least for now]]

rem generate apk and sign it 
rem https://stackoverflow.com/questions/26449512/how-to-create-a-signed-apk-file-using-cordova-command-line-interface/26450074#26450074

rem have to update versioncode and version to publish new version
cd \myproject\cordova
"....\....\notepad++.exe" config.xml [[note: change version and save]]
pause

cd \myproject\cordova\
start /wait cordova build --release android

copy ...\....\mykey.keystore \myproject\cordova\
cd \myproject\cordova\platforms\android\build\outputs\apk\
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore mykey.keystore android-armv7-release-unsigned.apk IntegraComexApps

del android-armv7-release.apk
...\AppData\Local\Android\android-sdk\build-tools\27.0.2\zipalign -v 4 android-armv7-release-unsigned.apk android-armv7-release.apk
del android-armv7-release-unsigned.apk
explorer .
cd \myproject
```

**Comment by caiobiodere** [comment]
You probably are going to try using the new 2.0.0 version and cordova build :+1:
