### ISSUE TITLE
babel-core error

### ISSUE THREAD

**Issue by mehrancodes** [centrual/cordova-template-framework7-vue-webpack#131]
I've got the below error msg when running `cordova run browser -- --live-reload`:

`Module build failed: Error: Cannot find module 'babel-core'`

After moving these three lines from dependencies to devDependencies, everything works fine:

package.json
```
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.1"
```

**Comment by caiobiodere** [comment]
Thanks @mehranrasulian ! 👍
