### ISSUE TITLE
main.scss - not work

### ISSUE THREAD

**Issue by VisualMafia** [centrual/cordova-template-framework7-vue-webpack#138]
Styles from this file do not work. Most likely, it needs to be connected separately?

**Comment by VisualMafia** [comment]
fix: add <style src="./assets/sass/main.scss" lang="scss"></style> to main.vue

**Comment by caiobiodere** [comment]
You can also use putting the scss reference on main.js file like this:

`import AppStyles from './assets/sass/main.scss'`

[main.js example](https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/blob/master/template_src/src/main.js)

**Comment by VisualMafia** [comment]
yeah, thanks!
