### ISSUE TITLE
please add rtl

### ISSUE THREAD

**Issue by vahidalvandi** [centrual/cordova-template-framework7-vue-webpack#140]
please add rtl

**Comment by caiobiodere** [comment]
hey @vahidalvandi is this what are you looking for?

[Webpack rtl plugin](https://github.com/romainberger/webpack-rtl-plugin)

**Comment by vahidalvandi** [comment]
hi . yes

**Comment by vahidalvandi** [comment]
f7 support rtl ! but how use it ,

**Comment by vahidalvandi** [comment]
https://framework7.io/docs/rtl-layout.html

**Comment by caiobiodere** [comment]
@vahidalvandi if you wanna use just the framework 7 rtl file, just use like this in your main.js file:

```
// Import F7 iOS Icons
import Framework7RLTCSS from 'framework7/css/framework7.rlt.css'
```
