### ISSUE TITLE
Update to latest version of modules and template

### ISSUE THREAD

**Issue by f0b04707** [centrual/cordova-template-framework7-vue-webpack#141]
Hi !

Thanks for the great template ! How do you update to the latest version of the template and modules ? As an example, Framework7 release framework7-icons v2.

Thanks !

**Comment by ngangchill** [comment]
this template throws error with npm deprecation error

![capture](https://user-images.githubusercontent.com/4242225/51090757-1d4ddf80-17ab-11e9-837a-c1cccbccffc2.PNG)

**Comment by caiobiodere** [comment]
hey @WhistleMaster I just finished the updates and everything :) Please use the last release: [2.3.0 - Release](https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/releases/tag/2.3.0)

**Comment by f0b04707** [comment]
@caiobiodere thanks ! How do you update an existing project to the latest version ?

**Comment by caiobiodere** [comment]
@WhistleMaster you can use this command to have a check:

Check the latest version: `npm outdate`
