### ISSUE TITLE
Obfuscator?

### ISSUE THREAD

**Issue by VisualMafia** [centrual/cordova-template-framework7-vue-webpack#144]
Someone added obfuscator? Everything that did not try, breaks the application.

**Comment by caiobiodere** [comment]
hey @VisualMafia can you explain it better for us?

**Comment by VisualMafia** [comment]
> hey @VisualMafia can you explain it better for us?

If someone unpacks * .apk and opens * .js, it will not be able to easily see the source code. This is good for safety. But everything I tried encodes the code, but breaks the application.

**Comment by VisualMafia** [comment]
really do this?

**Comment by caiobiodere** [comment]
but why do u need to unpack your .apk files? can you describe it better?

**Comment by VisualMafia** [comment]
Anyone can unpack * .apk and open * .js and see the code that I would not like to show.

**Comment by itsyub** [comment]
> Anyone can unpack * .apk and open * .js and see the code that I would not like to show.

@VisualMafia Have you tried [this encryption plugin](https://github.com/tkyaji/cordova-plugin-crypt-file) .

**Comment by VisualMafia** [comment]
> > Anyone can unpack * .apk and open * .js and see the code that I would not like to show.
> 
> @VisualMafia Have you tried [this encryption plugin](https://github.com/tkyaji/cordova-plugin-crypt-file) .

Thanks, the plugin is good, but it breaks everything in this build. And if you use the methods Vue is the same. As I understand it, the problem is in index.html. What could be the problem?

**Comment by VisualMafia** [comment]
I use https://github.com/javascript-obfuscator/webpack-obfuscator - all ok. But, work only for release.

**Comment by ajcool2k** [comment]
> Anyone can unpack * .apk and open * .js and see the code that I would not like to show.

Doubt there's much you can do about it because your client will always be able to read your code in plaintext since you decided to go by a plaintext runtime script language. Obfuscator won't protect your code since you could easily beautify it again.

**Comment by VisualMafia** [comment]
> > Anyone can unpack * .apk and open * .js and see the code that I would not like to show.
> 
> Doubt there's much you can do about it because your client will always be able to read your code in plaintext since you decided to go by a plaintext runtime script language. Obfuscator won't protect your code since you could easily beautify it again.

In this case, the protection is not from customers. I don't want my code to be read or copied easily.

**Comment by caiobiodere** [comment]
I liked your suggestion - https://github.com/javascript-obfuscator/webpack-obfuscator

I will probably think to add this later, thank you @VisualMafia !
