### ISSUE TITLE
how i can import same compoents instead all ?

### ISSUE THREAD

**Issue by vahidalvandi** [centrual/cordova-template-framework7-vue-webpack#146]
import { f7List, f7ListItem, f7Navbar } from 'framework7-vue';

https://framework7.io/vue/installation.html

**Comment by caiobiodere** [comment]
I didn't understand your question, you are already importing specific components aren't you?

**Comment by vahidalvandi** [comment]
i need use same component instead bundle maybe this can optimize load and animations

**Comment by ajcool2k** [comment]
I believe you are on the right track. You are only using f7List, f7ListItem and f7Navbar not the whole package by your import call. [Module](https://framework7.io/vue/package.html#es-module)

**Comment by caiobiodere** [comment]
@vahidalvandi I think you have been doing pretty well, don't worry because as @ajcool2k said you are already doing it by using bundles
