### ISSUE TITLE
Please update to framework v4 )) Thanks!

### ISSUE THREAD

**Issue by khudia** [centrual/cordova-template-framework7-vue-webpack#147]

**Comment by donotlb** [comment]
> Due to CSS variables and some other legacy features removed in v4, it will be the framework for modern devices. No IE and Android <5 support at all! Supporting such old browsers just holds us back in terms of new features development and framework evolution, so no more old browsers.

refer to: [The Best Framework7 Yet. What Is New In v4](https://blog.framework7.io/the-best-framework7-yet-what-is-new-in-v4-74b2b467047c)

**Comment by ajcool2k** [comment]
I upgraded my vue-webpack-f7 setup yesterday. It's really not a big issue. [Migration To Framework7 v4](https://blog.framework7.io/migration-to-framework7-v4-89d1ce49f4c0)

**Comment by caiobiodere** [comment]
Attending what you guys asked a new version related to framework7 4 version has been pushed and is now live!

**Comment by itsyub** [comment]
@caiobiodere  Framework7-4.0.0 doesn't support older browsers. Can you please create tag/branch for 3.0.0, so the user can select which framework7 version they want? For example like [this](https://github.com/lean/phaser-es6-webpack#phaser-3-supported-in-this-branch-httpsgithubcomleanphaser-es6-webpacktreephaser3)

**Comment by caiobiodere** [comment]
@itsyub good idea! I will probably create a tag regarding that I'm also creating more templates using tags

**Comment by khudia** [comment]
Thanks for update!
