### ISSUE TITLE
ios build error: requires a provisioning profile

### ISSUE THREAD

**Issue by casyalex** [centrual/cordova-template-framework7-vue-webpack#149]
HI,
I build the project by using `cordova build ios` then failed with missing provisoning file.
But it works on Xcode by import the provisionFIle manually. 
```
Error Domain=IDEProvisioningErrorDomain Code=9 ""Defect Claim Photo Upload Tool for iPad.app" requires a provisioning profile." UserInfo={NSLocalizedDescription="Defect Claim Photo Upload Tool for iPad.app" requires a provisioning profile., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}
```
My project need CICD, so i can't build it by Xcode everytime. 
Here is my build.json setting:
```
{
  "ios": {
    "release": {
      "buildFlag": [
        "-UseModernBuildSystem=0"
      ]
    },
    "development": {
        "codeSignIdentitiy": "iPhone Developer",
        "developmentTeam": "*****3H97Z",
        "provisioningProfile": "ce6d5fb1-****-4cfb-****-731f2e329b90",
        "packageType": "development"
    },
    "debug": {
        "codeSignIdentitiy": "iPhone Developer",
        "developmentTeam": "*****3H97Z",
        "provisioningProfile": "ce6d5fb1-****-4cfb-****-731f2e329b90",
        "packageType": "development"
    }
  }
}
```
I'm sure the provisioningFile is in the my ~Libary/**** location, and all the names or IDs are correct.

**Comment by itsyub** [comment]
@casyalex  For CICD,  why don't you use [fastlane](https://docs.fastlane.tools/getting-started/ios/appstore-deployment/).

**Comment by casyalex** [comment]
Problem solved，cordova-ios doesn‘t support Xcode 10.
set Legacybuildmode and archive success. 
```
      "buildFlag": [
        "-UseModernBuildSystem=0"
      ]
```
@itsyub Thank you, learning on this now.

**Comment by caiobiodere** [comment]
hey @casyalex if you follow this link you should be fine 👍 
[build.json](https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/blob/master/template_src/build.json)
