### ISSUE TITLE
Cordova 9

### ISSUE THREAD

**Issue by Overman775** [centrual/cordova-template-framework7-vue-webpack#152]
Hi! On cordova v9 drop dependency on Q. Need rewrite cordova hooks...
https://github.com/apache/cordova-lib/pull/710

When we cordova run an error appears:
`Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.`

**Comment by plussoftjo** [comment]
just back to cordova 8.1.2

npm uninstall -g cordova
npm install -g cordova@8.1.2

when owner this rep update the dependencies to cordova 9 you can update it

**Comment by caiobiodere** [comment]
All issues regarding Cordova 9.0.0 new version have been fixed, you guys can use it! thank you guys 👍
