### ISSUE TITLE
Cannot find module 'q'

### ISSUE THREAD

**Issue by cyrusonline** [centrual/cordova-template-framework7-vue-webpack#154]
Cannot find module 'q' when platform add browser

**Comment by Overman775** [comment]
Update template hooks https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/issues/152

**Comment by caiobiodere** [comment]
Please update your Cordova version to the new 9.0.0.

If you don't know how to do it you can see at [Cordova Installation](https://cordova.apache.org/docs/en/latest/guide/cli/index.html)
