### ISSUE TITLE
app run slow in my iphone8

### ISSUE THREAD

**Issue by lingjiawen** [centrual/cordova-template-framework7-vue-webpack#155]
Hello! I have used the command "cordova run ios" to install app, but the App running speed was slow when I do any operation. However,  the same problem didn't happen in Android platform and browser.

**Comment by lingjiawen** [comment]
I used "webpack.release ", then the command "cordova run ios" throwed a error:
" cordova-template-framework7-vue-webpack/template_src/node_modules/webpack-cli/bin/cli.js:231
throw err;"

**Comment by lingjiawen** [comment]
Do u have any suggestion for me? Thanks very much

**Comment by caiobiodere** [comment]
@lingjiawen did you try this command? 
`cordova run ios -- --lr`

**Comment by lingjiawen** [comment]
@caiobiodere yep i did, the command caused the same problem: app running slow in ios platform, all operations received about 1s delay

**Comment by caiobiodere** [comment]
not sure if it is correct but seems that iOS doesn't like Framework7 Vue components [Reference](https://stackoverflow.com/questions/52889691/accordion-animation-is-really-slow-in-ios-framework7-vue-app), anyway I am still searching for better answers

**Comment by caiobiodere** [comment]
@lingjiawen just to you know that I found the exactly problem, working on it

https://github.com/lasselaakkonen/fastclick/tree/fix-ios-11-3-event-timestamps

**Comment by caiobiodere** [comment]
@lingjiawen All delay bugs have been fixed and pushed! Please check again using the new 2.3.8 version -> [Release 2.3.8](https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/releases/tag/2.3.8)
