### ISSUE TITLE
framework7-vue as bundle

### ISSUE THREAD

**Issue by daxpunk** [centrual/cordova-template-framework7-vue-webpack#157]
Hi,

Why do you not include Framework7 vue as bundle in main.js:
`import Framework7Vue from 'framework7-vue/framework7-vue.esm.bundle';`

It permit to have a more light code in pages non ?

Dax

**Comment by caiobiodere** [comment]
Hi @daxpunk,

I was wondering the same when I made this change, but if you think that you are only using some components in some pages it's actually a good thought

**Comment by daxpunk** [comment]
Sure, I tell this just because it's a template, it's easiest to start a new project with lightest files, no?

**Comment by caiobiodere** [comment]
Yes it is for primary purposes, but my idea is to put you people in a better path
