### ISSUE TITLE
Can't resolve framework7/css/framework7.bundle.min.css

### ISSUE THREAD

**Issue by lulumalik** [centrual/cordova-template-framework7-vue-webpack#159]
Hmm.. there are something missing in my modules 

ERROR in ./src/main.js
Module not found: Error: Can't resolve 'framework7/css/framework7.bundle.min.css'

and there nothing file like framework7.bundle.min.css , or i missing something ?

**Comment by lulumalik** [comment]
after i read this https://blog.framework7.io/migration-to-framework7-v4-89d1ce49f4c0 

I tried importing the previous css, which was .min.css, and it was running normally but not completely css loaded

**Comment by caiobiodere** [comment]
Please check the latest 2.3.9 version!
