### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by kuez** [centrual/cordova-template-framework7-vue-webpack#16]
Hi, i have this issue after to try to add some platform:

PS D:\***> cordova platform add android
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: ************
        Name: *********
        Activity: MainActivity
        Android target: android-25
Subproject Path: CordovaLib
Android project created with cordova-android@6.1.2
Error: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

The platform is added, but, if i try "cordova run android" i have the same issue: 

PS D:\****> cordova run android
Error: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

Some idea? tnk!

**Comment by centrual** [comment]
Update your nodejs version to > 6.5.0
