### ISSUE TITLE
cordova build browser --release Error

### ISSUE THREAD

**Issue by cemarta7** [centrual/cordova-template-framework7-vue-webpack#162]
cordova build browser --release
gives this error 

ERROR in 9594cda895669512af1a.main.js from UglifyJs
Unexpected token: name «supportsPassive», expected: punc «;» [9594cda895669512af1a.main.js:149346,4]

any ideas?

**Comment by caiobiodere** [comment]
Are you using the last 2.3.9 template version? Because everything worked as expected here, if not I would suggest starting a new one from scratch to see that working well.

I used exactly this build -> `cordova build browser --release`

**Comment by caiobiodere** [comment]
@cemarta7  I've actually found the problem please follow this webpack release file:

https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/blob/master/template_src/config/webpack.release.js

**Comment by cemarta7** [comment]
@caiobiodere thanks for the help that actually fix one of my problems and solve my issue by removing a library. Thanks for the quick answer. I will be sure to patreon this project
