### ISSUE TITLE
cordova build android --release Error

### ISSUE THREAD

**Issue by patrykKlimczak** [centrual/cordova-template-framework7-vue-webpack#163]
Run: `cordova build --release android` 

```
Error happened when webpack build: Error: Command failed: "/home/admin/app/node_modules/.bin/webpack" --env.release
/home/admin/app/node_modules/webpack-cli/bin/cli.js:74
				throw err;
				^

ReferenceError: path is not defined
```

Any idea?

**Comment by phanviet** [comment]
@patrykKlimczak 

Add: `const path = require('path');` in `config/webpack.release.js`

**Comment by patrykKlimczak** [comment]
Add this file and run, but I have the next problem:

```
ERROR in ./node_modules/framework7-icons/css/framework7-icons.css 1:0
Module parse failed: Unexpected character '@' (1:0)
```

**Comment by khudia** [comment]
Yes i got the same errors. Can't build release

**Comment by VisualMafia** [comment]
I have the same thing

**Comment by khudia** [comment]
I found how to fix it) (and allready published app by this way) Since google needs app bunddle and not apk to release your app, you need to create keystone for your app then load your app to android studio, then create app bunndle (release) with keystone created and upload app.abb to google console for review! Thats all.))

**Comment by caiobiodere** [comment]
Are you guys using the last 2.3.9 template version? Because everything worked as expected here, if not I would suggest starting a new one from scratch to see that working well.

I used exactly this build -> `cordova build android --release`

**Comment by khudia** [comment]
how to update template version in dev project?

**Comment by khudia** [comment]
> Are you guys using the last 2.3.9 template version? Because everything worked as expected here, if not I would suggest starting a new one from scratch to see that working well.
> 
> I used exactly this build -> `cordova build android --release`

Just created clean project from template,added platform, run build = the same error!

**Comment by caiobiodere** [comment]
hey @khudia, I've actually found the problem please follow this webpack release file :

https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/blob/master/template_src/config/webpack.release.js

**Comment by VisualMafia** [comment]
Good, work, thanks!

**Comment by khudia** [comment]
> hey @khudia, I've actually found the problem please follow this webpack release file :
> 
> https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/blob/master/template_src/config/webpack.release.js

Thanks! It works. But as i say google now needs *.aab file to publish)
