### ISSUE TITLE
cordova run android -- --lr Alert gap_init:3

### ISSUE THREAD

**Issue by patrykKlimczak** [centrual/cordova-template-framework7-vue-webpack#164]
Run: `cordova run android -- --lr`

Everytime when refresh to app i see 4 alert:

`gap_init:3`

`gap:[0,"CoreAndroid","messageChannel","CoreAndroidxxxx"]`

`gap:[0,"CoreAndroid","show","CoreAndroidxxxx"]`

`gap:[0,"CoreAndroid","overrideBackbutton","CoreAndroidxxxx"]`

Any idea?

**Comment by caiobiodere** [comment]
Are you using the last 2.3.9 template version? Because no errors were showing to me, if not I would suggest starting a new one from scratch to see that working well.

I used exactly this command -> `cordova run android -- --lr`
