### ISSUE TITLE
Version 2.3.9 - ES Module

### ISSUE THREAD

**Issue by VisualMafia** [centrual/cordova-template-framework7-vue-webpack#166]
Version 2.3.9 - ES Module. You need to add components separately. This is not very convenient. I would add two options to the assembly so that you can choose.

All components (Bundle)
// Import Framework7
import Framework7 from 'framework7/framework7.esm.bundle.js';

// Import Framework7 Vue
import Framework7Vue from 'framework7-vue/framework7-vue.esm.bundle.js';

**Comment by caiobiodere** [comment]
Can you show me a better explanation to use components as a bundle instead of separately? For me, if I use them individually, I can have a better performance because I would use only as needed
 
Thanks for your help

**Comment by VisualMafia** [comment]
Previous versions were Bundle. According to this, if you update an existing application, you can not immediately understand what is wrong with. Is there a difference in performance between Bundle and ES Module? I always use the Bundle, everything works quickly.

**Comment by caiobiodere** [comment]
@VisualMafia I've done the changes to the whole bundle right here: https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/releases/tag/2.4.1
