### ISSUE TITLE
overswipe event bug in any device

### ISSUE THREAD

**Issue by A1Gard** [centrual/cordova-template-framework7-vue-webpack#167]
I try to create a project with this framework but I seen a bug in `swipeout` with `overswipe`.

### Explain more:
 in[ this ref ](https://framework7.io/docs/swipeout.html#overswipe) write : 

> `
With overswipe, script will automatically trigger "click" event on overswipe button, so you need to add appropriate event listener to this button`

but now this feature not work in the this package.

### What is i try:

I try use exactly what I seen in[ this page ](https://framework7.io/docs/swipeout.html#overswipe)but isn't work.

I try in[ `jsfiddle` ](https://jsfiddle.net/60y4xw2f/2/)to sure that bug not form framwork7-vue it's worked :( 

At last action try to update `framework7` & `framework7-vue` to latest version `4.4.3` but is not work in any device yet.

### notes
 **The `overswipe` event not work left and right both but the delete working good for me**
**And the project has `no error` in console browser**

please help to fix this problem.

**Comment by caiobiodere** [comment]
That's not a real template issue but I will try to help you soon

**Comment by A1Gard** [comment]
@caiobiodere the select checking is not work too :( You can test it.

Why it's as a bug!

**Comment by farzady** [comment]
I have the same problem too, can someone be kind and answer!

**Comment by caiobiodere** [comment]
Okay, I've fixed your problem it was happening because the Vue page was using separate components instead of the whole bundle. If you want to check it out, please go to the about page on the new template version.

Please check this last version: https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/releases/tag/2.4.1

**Comment by farzady** [comment]
@caiobiodere with which commands i can install the new update ?
```
1. 
cordova create <project_create_dir> [com.example.projectname] [ProjectClassName] --template cordova-template-framework7-vue-webpack

2.
cordova create cordova-template com.template DefaultTemplate --template git://github.com/caiobiodere/cordova-template-framework7-vue-webpack.git#master

3.
cordova create cordova-template com.template DefaultTemplate --template git://github.com/caiobiodere/cordova-template-framework7-vue-webpack.git#feature/v3-default-template
```
i have tested these commands but it does not working ..
I wonder Is it possible meybe it has been cached?

**Comment by caiobiodere** [comment]
this command should do the work:
`cordova create <project_create_dir> [com.example.projectname] [ProjectClassName] --template cordova-template-framework7-vue-webpack
`

have you checked if your Cordova and npm versions are up to date?

**Comment by A1Gard** [comment]
@caiobiodere It's work find Thanks for your help
