### ISSUE TITLE
src/assets/static/images not copied to phonegap platforms

### ISSUE THREAD

**Issue by coedycode** [centrual/cordova-template-framework7-vue-webpack#17]
Hi, I've added a favicon.png file to the src/assets/static/images directory in my project, but 

`phonegap build browser`

doesn't copy it to anywhere.

Is there something in a config file that needs turning on?

**Comment by centrual** [comment]
You need to require image files like `require('./assets/static/images/imagename.png')` in main.js (or somewhere else linked with main.js).

also you need to use return value of require command. Because path and image name will change after compile like `abcdefghjklmno.png`.

**Comment by coedycode** [comment]
Thanks for the explanation, I hadn't realised webpack did that, I thought it only handled the js and css build processes.

**Comment by centrual** [comment]
Hello @coedycode 

We have 1 more option now. You can add your image file to static folder and use like:

``` html
<img src="static/your_image.png">
```

Have a great day!
