### ISSUE TITLE
Live reload & API requests

### ISSUE THREAD

**Issue by VisualMafia** [centrual/cordova-template-framework7-vue-webpack#170]
I use last version.
Live reload & API requests not working.
Only Request Method: OPTIONS
How can I fix this so that all types of requests are available, as in a simple build?

**Comment by caiobiodere** [comment]
Oh, that's weird, Could you explain to us how are you building and using those API's, please?

**Comment by VisualMafia** [comment]
I use Axios. If i build apk or IOS, not problems. Problem only If i run this (sample): cordova run android -- --lr

**Comment by caiobiodere** [comment]
is that working in iOS devices? cordova run ios -- --lr

**Comment by VisualMafia** [comment]
No. I use default webview.

**Comment by VisualMafia** [comment]
If add this to server, then working: access-control-allow-headers: authorization,Authorization,access-control-allow-origin,Access-Control-Allow-Headers
