### ISSUE TITLE
how do use admob

### ISSUE THREAD

**Issue by ducdm87** [centrual/cordova-template-framework7-vue-webpack#173]
I am using this template for my app. I want to use [phonegap admob](https://www.npmjs.com/package/phonegap-admob). I didn't found document say about it.
I try use admob in code vue file, but admob is undefined.

Please help me.

**Comment by caiobiodere** [comment]
this is duplicated of https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/issues/111
