### ISSUE TITLE
platform browser on macos

### ISSUE THREAD

**Issue by khudia** [centrual/cordova-template-framework7-vue-webpack#177]
First i'm building all things for browser platform and then add native functionality but when i run 
"cordova run browser -- --lr" on win10 then all is good and i can work with, for example, native-storage-plugin. But if i do the same on my note (macos mohave) then i got error 
"http://127.0.0.1:8081/platform_cordova_files/browser/cordova.js 404 Not found" so no plugin that supports browser platform not works(   Hot reload works fine.
And one more thing!! If i run "cordova build browser" on Windows10 then cordova.js works fine but if i build on MacOs then it doesn't work again(

**Comment by caiobiodere** [comment]
Hi @khudia hope you are having a good day, I just did some tests with your comments and everything seems to work perfectly now, could you please try it again with the new [2.4.3 Version](https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/releases/tag/2.4.3)

**Comment by caiobiodere** [comment]
I am considering it as closed. Please let me know in case of any errors appears to you
