### ISSUE TITLE
build --release is failing in webpack

### ISSUE THREAD

**Issue by Em-AK** [centrual/cordova-template-framework7-vue-webpack#18]
cordova build android
is successfuly building in `platforms/android/build/outputs/apk/android-debug.apk`

But when I want to build a release with

    cordova build android --release

webpack build is failing with : 

```
Before deploy hook started...
Checking is node modules installed...
Node modules already installed.
Starting webpack build...
Error happened when webpack build: Error: Command failed: /home/emak/code/portrait/node_modules/.bin/webpack --env.release
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
clean-webpack-plugin: /home/emak/code/portrait/www has been removed.
(node:16644) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/is
sues/56                                                                                                                                                       parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

Webpack build completed to www folder successfully!
Error happened on main chain:
Error: Error happened when webpack build: Error: Command failed: /home/emak/code/portrait/node_modules/.bin/webpack --env.release
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
clean-webpack-plugin: /home/emak/code/portrait/www has been removed.
(node:16644) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/is
sues/56                                                                                                                                                       parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

    at exec (/home/emak/code/portrait/hooks/hookers.js:171:19)
    at ChildProcess.exithandler (child_process.js:218:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: Error happened when webpack build: Error: Command failed: /home/emak/code/portrait/node_modules/.bin/webpack --env.release
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
clean-webpack-plugin: /home/emak/code/portrait/www has been removed.
(node:16644) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/is
sues/56                                                                                                                                                       parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```

I tried to change `webpack.config.js:L77-78` according to this messages without success.

```
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
```

**Comment by Em-AK** [comment]
My current workaround is to launch 

    cordova prepare

then 

    cordova compile android --release

so that webpack compiles as usual without the release flag. The outputed JS may not be optimal but it runs.

**Comment by centrual** [comment]
Are you using latest version of template?

**Comment by Em-AK** [comment]
No, I am running 1.0.6

I will upgrade to the latest version and keep you posted. Is there another way than manually updating the files that changed since 1.0.6 to upgrade ?

**Comment by centrual** [comment]
replace your project's
``` bash
webpack/
hooks/

directories and

package.json
webpack.config.js
```

files with current version's. (check template_src folder)

**Comment by centrual** [comment]
Is problem fixed?

**Comment by centrual** [comment]
Hello @Em-AK;

I updated the dependencies and tested in my local. Please check one more time.

Have a great day!

**Comment by coedycode** [comment]
Hi @Em-AK I've been seeing similar error output when running a build release.

In my case I found running the webpack process on it's own

`./node_modules/.bin/webpack --env.release`

gave a more verbose error report, and the problems turned out to be Uglifyjs finding syntax errors in my vue components (I've been using ES2105 and there's no babel step in the release build, but the ES2015 is all supported by chrome so in development there were no problems. ).

The vue-loader will transpile if there's .bablerc with { "presets": ["es2015"] } in the root directory.

**Comment by centrual** [comment]
@coedycode I updated the template, can you test with latest update?

Thank you so much 😃

**Comment by coedycode** [comment]
@centrual  I've updated my copy to the latest webpack config and hookers, with the .bablerc removed I get  similar error messages to before, but with .bablerc there the build works fine.

Thanks for this great build tool btw, it's really helped me get started with phonegap.

**Comment by centrual** [comment]
Hello Richard;

I changed uglifyjs plugin to another one. Also, i updated dependencies. So please create new project and move your project files inside it.

Have a great Day!

**Comment by centrual** [comment]
I tested the latest version, because of that i closing the issue.

**Comment by YuannaLiang** [comment]
Is problem fixed?
