### ISSUE TITLE
 cordova emulate android  doesn't work

### ISSUE THREAD

**Issue by PaulMaly** [centrual/cordova-template-framework7-vue-webpack#2]
Error: Error happened when webpack build: Error: stdout maxBuffer exceeded

**Comment by centrual** [comment]
Hello @PaulMaly

I saw same error in mac os. i waiting `extract-text-webpack-plugin` release for next update.
I know the fixes, but we need to wait some more days for update. Because some problems happening in `extract-text-webpack-plugin`.

Have a great day!

**Comment by centrual** [comment]
Hello @PaulMaly 

I updated the template. Can you read instructions and check one more time?

Thank you so much.
Have a great day!
