### ISSUE TITLE
Add Cordova Browser-Sync Plugin ? 

### ISSUE THREAD

**Issue by cuduy197** [centrual/cordova-template-framework7-vue-webpack#20]
https://github.com/nparashuram/cordova-plugin-browsersync 

Will you add this plugin ??

**Comment by centrual** [comment]
Hello @cuduy197 

I started with it, but changed to webpack-dev-server which has hot-code-push. Please read the informations about template from https://github.com/centrual/cordova-template-framework7-vue-webpack before start project.

Have a great day!
