### ISSUE TITLE
Material Theme?

### ISSUE THREAD

**Issue by baberuth22** [centrual/cordova-template-framework7-vue-webpack#21]
Can I use the material theme?  I imagine it would require some components to be material specific as there dom is different.  Or perhaps the components can make use of v-if="$theme.ios" and v-if="$theme.material".

I

**Comment by centrual** [comment]
You can use every feature of framework7 and framework7-vue. Just look at the src/main.js for imports. Also [framework7-cli](https://github.com/nolimits4web/framework7-cli) can helps you for make app with material and ios at same time.
