### ISSUE TITLE
How to make this template compatible to both platform?

### ISSUE THREAD

**Issue by eltonmkw** [centrual/cordova-template-framework7-vue-webpack#22]
Hi,
I'm looking forward for this template do support for both Android and iOS platform. With this compatibility, I can develop much powerful app with its dynamically.
Thanks! 😄

Refer: https://framework7.io/tutorials/maintain-both-ios-and-material-themes-in-single-app.html

**Comment by centrual** [comment]
Actually, you can, but it's not very easy also not performant.
I want to contribute to https://github.com/nolimits4web/framework7-cli . In f7-cli very easy to manage ios and android.

**Comment by eltonmkw** [comment]
Great insight, thank you @centrual , I didn't know Framework7 provides CLI across these times. Haha :rofl:
