### ISSUE TITLE
how to use <keep-alive> in this template

### ISSUE THREAD

**Issue by HoldSkill** [centrual/cordova-template-framework7-vue-webpack#24]
excuse me, how to use <keep-alive> in this template?
i want to judge the current page to remove css, but destroyed not working.
Thank you
````
var HomeIndexStyles = require('!style-loader/useable!css-loader!../../css/home/index.css');
……
mounted: function() {
   this.$nextTick(function() {
    HomeIndexStyles.use();
   }
},
destroyed: function() {
    HomeIndexStyles.unuse();
    console.log('销毁了HomeIndexStyles');
}

````

**Comment by centrual** [comment]
Hello @HoldSkill 

I am sorry for late response, i missed your issue.

It's not clear but i think it's about vue.js. You can ask this question to [vue gitter from here](https://gitter.im/vuejs/vue) if you want. I didn't used usable styles, so i don't know how i can fix it.

Have a great day!
