### ISSUE TITLE
How to config webpack "babel-loader" for js file? 

### ISSUE THREAD

**Issue by cuduy197** [centrual/cordova-template-framework7-vue-webpack#25]
Im want using babel-loader ? , i edit webpack config like this, app running but it only whitescreen.
How to config webpack "babel-loader" for js file? 
```
{ test: /\.js?$/, loader: 'babel-loader?presets[]=env&presets[]=stage-0', exclude: /node_modules/, enforce: 'pre' }
```

**Comment by cuduy197** [comment]
App running but only have whitescreen ...

**Comment by centrual** [comment]
This question not about this repository. You need to ask it to webpack community.

**Comment by centrual** [comment]
Answer: https://github.com/centrual/cordova-template-framework7-vue-webpack/issues/29
