### ISSUE TITLE
Where to place / How to reference SVGs for Phonegap use

### ISSUE THREAD

**Issue by joedeveloper** [centrual/cordova-template-framework7-vue-webpack#26]
I am running into issues using SVGs, during development I had placed svg files in `www/assets/subdirs/files.svg` - this was working fine.

When I then did a phonegap run android, I found that one of the hooks wiped out everything in www/

I then tried to place the svgs in:
src/assets/static/images/svg/subdirs/files.svg
and
src/static/images/svg/subdirs/files.svg

Neither seem to give me any joy, any hints?

**Comment by centrual** [comment]
You need to import your svg file. You can do this like:
`import mySvgImage from './../static/images/svg/subdirs/files.svg'`
it returns compiled dynamic address to `mySvgImage`.

You need to add variable in vue:
``` javascript
new Vue({
  data: {
    images: {
      mySvgImage: require('./../static/images/svg/subdirs/files.svg')
    }
  }
}
```

``` html
<img :src="images.mySvgImage">
```

**Comment by joedeveloper** [comment]
@centrual  Thank you for the insight

I hate to say it, but this seems like a pretty heavy approach - is there really no 'static' folder support? 

Would I have to do the same for say sound files? 
How would I end up dealing with run-time changes to which svg to show ( as a simple example I have hazard_default.svg, hazard_fast.svg and hazard_slow.svg - which are swapped depending on state). Some widgets have 10 different state based svgs, am I really forced to enumerate them all as data properties and pass them around?

Thanks for your time, in creating the template and also for pointing me in the right direction in this.

**Comment by centrual** [comment]
You are right. I'll add static folder soon.

**Comment by centrual** [comment]
Hello @joedeveloper 

I added static folder to project also it will automatically sync with www/static on live-reload. Please check latest version.

Have a great day!

**Comment by joedeveloper** [comment]
Thank you so much, will check it out shortly

**Comment by centrual** [comment]
Any updates?

**Comment by centrual** [comment]
I closing the issue, it seems fixed.

**Comment by joedeveloper** [comment]
Sorry for the late response, just cycled back to this project and thank you, it works for me.
