### ISSUE TITLE
Pleace help me using babel-loader . [Fixed]

### ISSUE THREAD

**Issue by cuduy197** [centrual/cordova-template-framework7-vue-webpack#29]
I try , but could you add babel loader to your template ? :+1:  
Because i want using `spread syntax `, plz help me.

**Comment by centrual** [comment]
1) Open command prompt
2) Go to your project directory ( cd your/project/directory )
3) npm i --save-dev babel-loader babel-plugin-transform-runtime babel-preset-env
4) Open webpack.config.js in your preferred editor
5) Change line 40:
`{test: /\.js?$/, loader: 'source-map-loader', enforce: 'pre'},`
to
``` javascript
{
    test: /\.js$/,
    exclude: /(node_modules|bower_components)/,
    use: {
      loader: 'babel-loader',
      options: {
        presets: ['env'],
        plugins: ['transform-runtime']
      }
    }
},
```
6) create .babelrc to your project root folder with following content:
``` json
{
  "presets": ["env"]
}
```

You can use babel loader now.

**Comment by cuduy197** [comment]
:+1:  Thanks you, it work :tada:

**Comment by centrual** [comment]
I closing the issue,

Have a great day!
