### ISSUE TITLE
use this.$router.load(...) in main.vue

### ISSUE THREAD

**Issue by cbrhex** [centrual/cordova-template-framework7-vue-webpack#3]
Hi. I need make a redirect in main.vue, but `this.$router` is undefined. How can I do that? thx.

**Comment by centrual** [comment]
Hello @Cyber-host i'll check this bug tomorrow.

Have a great day!

**Comment by centrual** [comment]
Hello @Cyber-host 

I checked the problem with this template and framework7's webpack template. Same problem exists in the Framework7's webpack template too. I opened issue at https://github.com/nolimits4web/Framework7-Vue-Webpack-Template/issues/11

Have a great day!

**Comment by centrual** [comment]
@Cyber-host Vladimir answered the question. Please look at:
https://github.com/nolimits4web/Framework7-Vue-Webpack-Template/issues/11

Have a great day!
