### ISSUE TITLE
How to load mp3 file ? 

### ISSUE THREAD

**Issue by cuduy197** [centrual/cordova-template-framework7-vue-webpack#31]
I want to using mp3 in my app .
 I using file-loader like this : 
` { test: /\.(png|jpe?g|gif|mp3)$/, loader: 'file-loader', options: { name: '[name].[ext]?[hash]' } },`

and require it in modules vuex  : 
`export const mp3 = {
    namespaced: true,
    state: {
        music: require('../../assets/static/mp3/music.mp3')
    },
    mutations: {}
};
`
But i can't using mp3? :confused:  what i'm do wrong? plz help me .

**Comment by centrual** [comment]
Hello @cuduy197 

I'm sorry but i can't help you for every webpack problem. Please ask this questions to webpack community: https://gitter.im/webpack/webpack

Have a great day.
