### ISSUE TITLE
HMR issue on main.vue

### ISSUE THREAD

**Issue by Matheo13** [centrual/cordova-template-framework7-vue-webpack#32]
Hi,

Thank you for your work.
It seems there is an issue with HMR on the first page.
When I try to modify the script tag inside main.vue, It reloads the entire page and I get a white screen, without any errors in the console, do you know why?
I was thinking it was due to modifications on my side but after I started with a new clone of the repo I have the same issue.

Thanks.

**Comment by centrual** [comment]
Hello @Matheo13 

I tested on clean project with this commands:
1) cordova create testproject --template cordova-template-framework7-vue-webpack
2) cd testproject
3) cordova platform add browser
4) cordova run browser -- --lr

and i tested to change main.vue file like:
1) Add new vue component
2) Remove vue component
3) Change property in vue component
4) Change text in vue component default slot
5) Change text in page
etc.

Every command worked fine on me. Can you share your
1) OS
2) NodeJs version: `node -v`
3) Installed modules in your project: `npm ls --depth=0`
4) Chrome developer console output after you changed the main.vue file

**Comment by Matheo13** [comment]
Thanks, I take a look on it soon.

**Comment by Matheo13** [comment]
I tried again, same issue:

OS: windows 10 64bits

```
λ node -v
v6.10.2
```

```
λ npm ls --depth=0
CordovaFramework7VueWebpackTemplate@1.0.0 C:\inetpub\wwwroot\new\testproject
+-- cheerio@0.22.0
+-- clean-webpack-plugin@0.1.16
+-- css-loader@0.27.3
+-- device.js@0.2.7 (git+https://github.com/matthewhudson/device.js.git#c655e7066d0255c8eb141fa994afe238fb69c379)
+-- epipebomb@1.0.0
+-- extract-text-webpack-plugin@2.1.0
+-- file-loader@0.10.1
+-- framework7@1.6.0
+-- framework7-vue@0.8.5
+-- html-loader@0.4.5
+-- html-webpack-plugin@2.28.0
+-- node-sass@4.5.2
+-- path@0.12.7
+-- sass-loader@6.0.3
+-- source-map-loader@0.2.1
+-- style-loader@0.13.2
+-- svg-url-loader@2.0.2
+-- uglify-js@2.8.22 (git://github.com/mishoo/UglifyJS2.git#278577f3cb75e72320564805ee91be63e5f9c806)
+-- uglifyjs-webpack-plugin@0.3.1
+-- url-loader@0.5.8
+-- vue@2.2.6
+-- vue-hot-reload-api@2.0.11
+-- vue-html-loader@1.2.4
+-- vue-loader@11.3.4
+-- vue-template-compiler@2.2.6
+-- webpack@2.3.3
`-- webpack-dev-server@2.4.2
```


![image](https://cloud.githubusercontent.com/assets/9080540/24963163/19d9fa02-1f9e-11e7-949a-fdadceb979b1.png)

**Comment by Matheo13** [comment]
(without the warnings it's the same)
``` 
npm --version
3.10.10
```

**Comment by Matheo13** [comment]
![image](https://cloud.githubusercontent.com/assets/9080540/24963871/1b25d398-1fa0-11e7-8f54-170cdea61e14.png)
The dom isn't empty.

**Comment by centrual** [comment]
I'm using same OS and same commands and it's working on me. So i can't reproduce in my computer. I can check the problem in your computer via teamviewer. If you want it please send email to centrual@outlook.com for private chat.

**Comment by Matheo13** [comment]
Ok, `framework7-root` class is missing on div#app after  HMR, but I don't know why.

**Comment by Matheo13** [comment]
could you send me your npm ls --depth=0?

**Comment by Matheo13** [comment]
It works if I set class="framework7-root" inside main.vue.
Can you explain me why is there both div#app in index.html and in main.vue?
I guess there is one for vue and one for framework7?

**Comment by centrual** [comment]
```
C:\xampp\htdocs\tmptest>npm ls --depth=0
CordovaFramework7VueWebpackTemplate@1.0.0

C:\xampp\htdocs\tmptest
+-- cheerio@0.22.0
+-- clean-webpack-plugin@0.1.16
+-- css-loader@0.27.3
+-- device.js@0.2.7 (git+https://github.com/matthewhudson/device.js.git#c655e7066d0255c8eb141fa994afe238fb69c379)
+-- epipebomb@1.0.0
+-- extract-text-webpack-plugin@2.1.0
+-- file-loader@0.10.1
+-- framework7@1.6.0
+-- framework7-vue@0.8.5
+-- html-loader@0.4.5
+-- html-webpack-plugin@2.28.0
+-- node-sass@4.5.2
+-- path@0.12.7
+-- sass-loader@6.0.3
+-- source-map-loader@0.2.1
+-- style-loader@0.13.2
+-- svg-url-loader@2.0.2
+-- uglify-js@2.8.22 (git://github.com/mishoo/UglifyJS2.git#278577f3cb75e72320564805ee91be63e5f9c806)
+-- uglifyjs-webpack-plugin@0.3.1
+-- url-loader@0.5.8
+-- vue@2.2.6
+-- vue-hot-reload-api@2.0.11
+-- vue-html-loader@1.2.4
+-- vue-loader@11.3.4
+-- vue-template-compiler@2.2.6
+-- webpack@2.3.3
`-- webpack-dev-server@2.4.2


C:\xampp\htdocs\tmptest>node -v
v7.8.0

C:\xampp\htdocs\tmptest>npm --v
4.2.0
```

**Comment by centrual** [comment]
I think one #app for f7 and the other #app for vue.

**Comment by Matheo13** [comment]
I guess I can close this issue, it works with the little hack, I have the same issue on others officials f7-vue starters, maybe I should duplicate it?
Thank you for your (fast) reply!
Have a nice day.
