### ISSUE TITLE
how to go to a page by url

### ISSUE THREAD

**Issue by HoldSkill** [centrual/cordova-template-framework7-vue-webpack#33]
hello~
when i try to use this url `http://127.0.0.1:8081/#/lecture/room/?id=1` to go to the `room.vue` page, the app will go to the index page ? why? thank you very much

**Comment by centrual** [comment]
Hello @HoldSkill 

Please ask this question to framework7 forums or gitter. I didn't used page urls and framework7 navigation before.

Have a great day.

**Comment by HoldSkill** [comment]
thank you ~
 Could you please help me how to use vue-router in this framework template?

**Comment by centrual** [comment]
Same as framework7. Yok can access framework7 from window.f7.
