### ISSUE TITLE
Error when project path have space in folder name

### ISSUE THREAD

**Issue by dawadam** [centrual/cordova-template-framework7-vue-webpack#34]
Small error when `sudo cordova run android` with space in project path.
I'm on linux.
Exemple with `/home/name/Documents/test cordova/project/` :
```
sudo cordova run android
Before deploy hook started...
Checking is node modules installed...
Node modules already installed.
Starting webpack build...
Error happened when webpack build: Error: Command failed: /home/name/Documents/test cordova/project/node_modules/.bin/webpack
/bin/sh: 1: /home/name/Documents/test: not found

```

**Comment by centrual** [comment]
Thanks for issue, i'll check soon.

**Comment by centrual** [comment]
Hello again @dawadam 

I fixed the issue and tested in windows. Please check with latest version (1.1.1). I'm waiting for your response for close the issue.

Have a great day!

**Comment by centrual** [comment]
Closing the issue...
