### ISSUE TITLE
Create cordova project from folder

### ISSUE THREAD

**Issue by lcaprini** [centrual/cordova-template-framework7-vue-webpack#36]
Hi,
I created a cordova app with your template with cordova cli and after that I commit in my git repo.
In a second PC I download sources with git's checkout, but when I try to execute any cordova cli command I've the following error:

> Error: Current working directory is not a Cordova-based project.

To make it works I had to create a  new cordova project ad after that I had to copy all files from my checkout to it, replacing all files (hooks, www, config.xml, ...)

There is another solution to "create" cordova app from your project folder?

**Comment by centrual** [comment]
Please create empty `www` folder in your project directory. Also please check [this issue](https://github.com/centrual/cordova-template-framework7-vue-webpack/issues/35) for detailed information about template.

Also, you need to create an app with this command:
`cordova create your_app_dir your.domain.address "Your App Name" --template cordova-template-framework7-vue-webpack`

**Comment by lcaprini** [comment]
Perfect! With empty `www` folder the project is now a Cordova project.
I added
```
/www/*
!.gitkeep
```
so my `www` folder remain in git repo but without dinamically created contents.
Thank you for your help.

-L
