### ISSUE TITLE
Android: Failed to load resource: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by ghost** [centrual/cordova-template-framework7-vue-webpack#37]
Hi,

I have some problems with the "livereload" function under android.
First I´ve created a new project, added platforms and tried to run it:

1: `cordova run browser -- --lr`   ----> Everyhing works fine, got directed to 127.0.0.1:8081

2: `cordova run android -- --lr`  ---> I got a connection error. 
![screenshot_20170425-084301](https://cloud.githubusercontent.com/assets/27993481/25372378/6d7136ca-2995-11e7-9c5c-67b794927e3b.png)

Will i have to do some additional configurations  (webpack.config.js) ????

Thx in advance ....

**Comment by centrual** [comment]
Hello @SgtPepper27 

It's happening to me too. The problem about webpack-dev-server's last version. It's webpack-dev-server bug. You can track the bug from https://github.com/webpack/webpack-dev-server/issues/882

Also, your problem can be about antivirus or system firewall. Please check firewall configurations.

If you are using emulator, problem can be related with emulator too.

Have a great day!

**Comment by centrual** [comment]
Hello again @SgtPepper27 

I updated the template to version 1.1.0. Please use the latest version. I'm waiting your response for close the issue.

Have a great day!

**Comment by ghost** [comment]
Perfect, thanks a lot !!

**Comment by centrual** [comment]
Your welcome @SgtPepper27 

Have a great day!

**Comment by sunflowerlb** [comment]
I also have this problem . @centrual  @SgtPepper27  Are you solved?

**Comment by u01jmg3** [comment]
I too am facing this issue. Is there a fix?

**Comment by u01jmg3** [comment]
@centrual: I too am facing this issue when live reloading to an Android phone **or** emulator.

Are there particular Webpack config settings to fix this issue? I am using the latest version of this template and webpack-dev-server but still getting a connection error.

Would greatly appreciate your help.

**Comment by thitemple** [comment]
I'm facing the same issue
