### ISSUE TITLE
Vue warn “style” is a reserved attribute

### ISSUE THREAD

**Issue by asifkilwani** [centrual/cordova-template-framework7-vue-webpack#39]
while testing vuejs + webpack starter template, in console I am seeing this error vue.common.js:431 [Vue warn]: “style” is a reserved attribute
![screen shot 2017-04-27 at 11 59 59](https://cloud.githubusercontent.com/assets/26161221/25478360/111c3f2a-2b41-11e7-9b8c-ed044d42d538.png)
 and cannot be used as component prop.

**Comment by centrual** [comment]
It's framework7-vue related issue. You can track the issue from https://github.com/nolimits4web/Framework7-Vue/issues/148.

**Comment by yannicklin** [comment]
Fixed?? I still found this issue unfixed.
