### ISSUE TITLE
How to import SASS with root path?

### ISSUE THREAD

**Issue by adi-works** [centrual/cordova-template-framework7-vue-webpack#41]
I'm trying to import a SASS partial, like so:

```
<style scoped lang="sass">
@import 'assets/sass/colors.scss';
</style>
```

It doesn't resolve though.

**Comment by adi-works** [comment]
Ok, apparently this works: `@import '~assets/sass/colors';`

Using tilde. Is that a part of native Webpack config or a plugin of sort? couldn't find it in Webpack docs.

**Comment by centrual** [comment]
scss is another lang inside of sass. So scss different than sass. I updated the package for scss support in one page component:
``` html
<style scoped src="./assets/sass/colors.scss" lang="scss"></style>
```

**Comment by adi-works** [comment]
Scss is not the problem as Sass compiles Scss just fine. The issue is resolved using tilde. Apparently you need that for a Sass import directive (`@import`). I just wonder where exactly it appears in the Webpack docs.

**Comment by centrual** [comment]
I think i didn't understand your question. My English not well enough. i am sorry for that.

I didn't used tilde before. But when i check in google i found this: https://github.com/webpack-contrib/sass-loader#imports

Is the problem resolved already?

**Comment by adi-works** [comment]
Yes
