### ISSUE TITLE
type check failed for prop "infiniteScrollDistance"

### ISSUE THREAD

**Issue by asifkilwani** [centrual/cordova-template-framework7-vue-webpack#45]
Defining scroll distance console throwing error.

<f7-page name="feeds" infinite-scroll @infinite="onInfiniteScroll" infinite-scroll-distance="100">

[Vue warn]: Invalid prop: type check failed for prop "infiniteScrollDistance". Expected Number, got String. 
(found in <F7Page>)

However in compiled version I can see data-distance attribute added to page-content
<div data-distance="100" class="page-content infinite-scroll">

**Comment by centrual** [comment]
Hello @asifkilwani 

It's vue or framework7-vue related question. Please don't ask vue related questions here. You can ask in gitter: https://gitter.im/vuejs/vue

If you want to bind non-string value to property, you need to use v-bind. Following code will work:
``` html
<f7-page name="feeds" infinite-scroll @infinite="onInfiniteScroll" :infinite-scroll-distance="100">
```

Have a great day!
