### ISSUE TITLE
White screen when created build version for Cordova

### ISSUE THREAD

**Issue by asifkilwani** [centrual/cordova-template-framework7-vue-webpack#46]
I used xCode to compiled the iOS app. When app installed and started, it's showing white screen. I have external js files placed in assets/js/. Those files are not moving to /www folder

**Comment by centrual** [comment]
Hello @asifkilwani 

Firstly you need to learn how webpack works for use this template. You can use static folder for static assets ( `<img src="static/your-image.jpg">` ) or you can assign a variable into the vue for non-static assets:
``` html
<template>
  <div id="your-page">
    <img :src="images.myImage">
  </div>
</template>

<script>
  export default {
    data() {
      return {
        images: {
          myImage: require('./../../images/your-image.jpg')
        }
      }
    }
  }
</script>
```

Have a great day!
