### ISSUE TITLE
Feature request: Vuex 

### ISSUE THREAD

**Issue by strixy** [centrual/cordova-template-framework7-vue-webpack#47]
Any interest in adding Vuex as well? I've used your project here twice and I like it. I look forward to using it more.

I find that adding Vuex is almost always my next step and even when it's not, it's only because I'm rolling my own for very small testing projects. In those cases, I would be just as happy to have Vuex already installed.

This is just a suggestion. You might have other plans or use cases to meet and if so, no worries at all.

I hate having to post this as an issue. Is there a better way to have this conversation? I'm relatively new to Github still.

Thank you for your efforts on this project already. Greatly appreciated.

**Comment by centrual** [comment]
Hello @strixy 

~Vuex not for everybody. So i haven't plan to add vuex into the template. But you can do it yourself. Check  https://github.com/centrual/cordova-template-framework7-vue-webpack/issues/40 please.~

I changed my mind, adding different versions of the template soon:
cordova-template-framework7-vue-vuex-babel-webpack
cordova-template-framework7-vue-vuex-webpack
cordova-template-framework7-vue-babel-webpack
cordova-template-framework7-babel-webpack
cordova-template-framework7-webpack
cordova-template-vue-vuex-babel-webpack
cordova-template-vue-vuex-webpack
cordova-template-vue-babel-webpack
cordova-template-vue-webpack
cordova-template-babel-webpack
cordova-template-webpack

Have a great day!

**Comment by strixy** [comment]
Thank you for agreeing to add Vuex. It appears in the official Vue documentation as the only alternative to DIY state management. 

Good idea to mention Babel. Come to think of it, don't you have Vueify already included as well? You should maybe mention that in the docs. That's a big win too.

When you say "Vuex not for everybody", what other options are there besides creating your own? I'm curious, is there a cool toy I haven't played with yet?

**Comment by luckynum7** [comment]
May I mention two JavaScript database here,

1. [PouchDB](https://pouchdb.com/): PouchDB is an open-source JavaScript database inspired by Apache CouchDB that is designed to run well within the browser.
2. [LokiJS](http://lokijs.org/): LokiJS is an in-memory database which prioritises performance over everything

I think both are very popular database for now. I used LokiJS in my project, with IndexedDb adapter (there's a [file adapter](https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters#simple-example-of-using-lokinativescriptadapter-) also.)

When use lokijs, there is a gotcha when build with webpack (`Cannot resolve module 'fs'`). And the solution: https://github.com/pugjs/pug-loader/issues/8#issuecomment-55568520 
```js
node: {
  fs: "empty"
}
```

There also someone mentioned config like `target: "electron"` can solve the `fs` problem https://github.com/webpack/webpack/issues/3012#issuecomment-248017259 for electron. And I found the `target` config [here](https://github.com/webpack/webpack/blob/6ba220d5216a8bd5db7166cc269650008ab64bb6/schemas/webpackOptionsSchema.json#L1041)

```json
    "target": {
      "anyOf": [
        {
          "enum": [
            "web",
            "webworker",
            "node",
            "async-node",
            "node-webkit",
            "atom",
            "electron",
            "electron-main",
            "electron-renderer"
          ]
        },
```

Will try to use `taget: "web"` to see if I can solve the `fs` module not found thing someday.

**Comment by strixy** [comment]
Thank you!

**Comment by yipcma** [comment]
cordova-template-framework7-vue-vuex-babel-webpack +1

**Comment by lroal** [comment]
cordova-template-framework7-vue-vuex-babel-webpack +1

**Comment by caiobiodere** [comment]
I created a new release that is using Vuex and babel features :)

you can check on (2.0.3):
https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/releases/tag/2.0.3
