### ISSUE TITLE
Dom7 not defined w/ Framework7 1.6.2

### ISSUE THREAD

**Issue by strixy** [centrual/cordova-template-framework7-vue-webpack#49]
A recent upgrade to F7 version 1.6.2 caused a Dom7 not defined error. Confirmed with clean install of current project.
```
Uncaught ReferenceError: Dom7 is not defined
    at a09b5db….main.js:24342
    at a09b5db….main.js:24447
    at Object.<anonymous> (a09b5db….main.js:28508)
    at Object.<anonymous> (a09b5db….main.js:28512)
    at __webpack_require__ (a09b5db….main.js:20)
    at Object.<anonymous> (a09b5db….main.js:34955)
    at __webpack_require__ (a09b5db….main.js:20)
    at module.exports.rawScriptExports (a09b5db….main.js:66)
    at a09b5db….main.js:69
```
Rolling back to Framework7 v1.6.0 works, but only as a workaround.
Dom7 becamse a standalone dependency (devDependency (only?)) for F7 at v1.6.2
Does that impact this project?

**Comment by boring2** [comment]
I have the same problem by using 1.6.3. It's because the version use strict so 'this' is not undefine. But it is framework7 issue, not cordova-template-framework7-vue-webpack problem.

**Comment by centrual** [comment]
I'll check when i become free.

**Comment by centrual** [comment]
Framework7 1.6.4 Released, please update with `npm update`
