### ISSUE TITLE
Vuex getter error during evaluation

### ISSUE THREAD

**Issue by mandalmanav** [centrual/cordova-template-framework7-vue-webpack#50]
i have added vuex and getting value of state as "error during evaluation"

![image](https://user-images.githubusercontent.com/28473795/27302214-b1a3cb16-5553-11e7-97ff-3a27e2ab7a4e.png)

here is my code

`<script>
    import { mapGetters } from 'vuex';
   
	export default{
		  computed:{
               
                ...mapGetters({
                    repositoryList:'getRepositoryList'
                })
            },
 
          
       data(){
                return {
                    list:[]
                }
            },
	}
</script>`

**Comment by ghost** [comment]
Seems that this is a syntax problem but not because of the template.

Try:
computed: {
   ...mapGetters(['getRepositoryList'])
}

and then you should have access to the getter like:

this.getRepositoryList()
