### ISSUE TITLE
Strict mode with node npm 8.2.1

### ISSUE THREAD

**Issue by asifkilwani** [centrual/cordova-template-framework7-vue-webpack#60]
When testing app for Android 5.1, console showing "use of const in strict mode".

I have node 8.2.1. I read few other issues in this repo but can't find solution for node greater than 6.5.

Wondering if compile to ES5 will solve problem for Android 4.x & 5.x?

**Comment by caiobiodere** [comment]
I will close because i think there isn't a big problem, let me know if you need more help on this situation
