### ISSUE TITLE
Postcss-loader and its autoprefixer in wepback build process

### ISSUE THREAD

**Issue by ryaposov** [centrual/cordova-template-framework7-vue-webpack#61]
Can't get postcss-loader autoprefixer work with this web pack config, could anyone help with there right config options?

Thanks in advance!

**Comment by caiobiodere** [comment]
hey @ryaposov you just need to configure web pack rules like this one:
`rules: [{test: /\.css$/, use: [ 'style-loader', 'postcss-loader' ]}]`

but please pay attention you need to remove next configurations that are using CSS rules, you can search for (/\.css$/)
