### ISSUE TITLE
Wrong cordova.js injected for browser with iOS/Android User-Agent

### ISSUE THREAD

**Issue by ryaposov** [centrual/cordova-template-framework7-vue-webpack#62]
**Problem:**
When running in hot-reload mode, with User-Agent that stands for Mobile "platform_cordova_files/ios/cordova.js" is injected in html instead of "platform_cordova_files/browser/cordova.js".

I'm not actually sure how, but that leads to that `deviceready` event is not firing.

**Steps to reproduce:**
1. Run `cordova run browser -- --live-reload`
2. Wait until Chrome is opened, or open `http://127.0.0.1:8081`
3. Open devtools and Toggle Device Toolbar (SHIFT+CMD+M for Mac) - this will set Mobile User Agent
4. Reload the page

![2017-08-16_23-30-45](https://user-images.githubusercontent.com/5815992/29386167-f4e2bc8e-82da-11e7-8b2e-a51ed96b20cf.png)

**Comment by centrual** [comment]
It seems you'r using Chrome in mobile mode. Mobile mode sets user agent as iPhone.

You need to create custom mobile phone profile and user agent.

**Comment by ryaposov** [comment]
Thanks for your answer! But what for I need to create custom mobile agent? 
"deviceready" is not supposed to fire in mobile browsers? Is it possible to get it fired in mobile browser?

**Comment by centrual** [comment]
Device ready will trigger if you load with browser user agent.

**Comment by ryaposov** [comment]
Well, as far as I know, all User-Agents are browser :)
If I open website in Mobile Safari browser, I open it sending server mobile safari user agent. And in this situation deviceready will not fire, just because I'm opening it in mobile browser, not desktop?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent

**Comment by josteph** [comment]
If you're on chrome, you're probably using Device Toolbar to when first loading the project.
Then, perhaps you have selected device like iPhone 6 when first loading the project, this will make `deviceJs` to detect it as ios platform.

I have tested it on actual android and ios devices and both works as expected (importing from correct platfrom).

**Comment by ryaposov** [comment]
What I'm talking is, when app is loaded in **browser** (not native WebView) - whatever it is iOS, Android or Desktop browser, **browser** cordova.js should be included.

User Agent for Mobile Safari and native iOS WebView would be the same, but the cordova.js is different. That's why it's not safe to use UserAgent condition.

Here, I'm providing screenshot that build is requesting iOS version of cordova, while it's browser, and the same would be if I would open it on Mobile Safari on iPhone.

![2017-11-29_15-36-35](https://user-images.githubusercontent.com/5815992/33380483-86dfd5e4-d51b-11e7-8066-27a671e84cc2.png)

**Comment by rlam3** [comment]
@ryaposov is this fixed yet? Or have you found a workaround?

**Comment by victoryhb** [comment]
The easiest way I have found to solve the problem is to add the following to config.xml:
`<preference name="OverrideUserAgent" value="Mozilla/5.0 Google" />`

**Comment by ryaposov** [comment]
@rlam3 no, I moved my project to my custom template based on [OnsenUI](https://github.com/OnsenUI/vue-cordova-webpack) template

**Comment by caiobiodere** [comment]
hey @ryaposov, did you try using the @victoryhb solution?

**Comment by rainfu** [comment]
@caiobiodere  that solution by @victoryhb  only has effect the first time ,when user refresh page with f5, i't can't work, 

i have pulled a solution to fix [this](https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/pull/135) ,it's get user device by user input cmd ,when user input 'cordova run browser...' ,thd body will inject '/browser/cordova.js' just soso.

**Comment by caiobiodere** [comment]
@rainfu thank you very much, I just added a new release called "2.1.1"

**Comment by linehammer** [comment]
Detecting mobile device using user agent isn't the best way to check if a user is using a mobile device since user agent strings can be spoofed easily. However, this method is still an easy way to check what device is being used by the user.

 There is a JavaScript API built-in for detecting media. The JavaScript window.matchMedia() method returns a MediaQueryList object representing the results of the specified CSS media query string. You can use this method to [detect  mobile device](http://net-informations.com/js/progs/mobile.htm) based on the CSS media query.
 
```
<script>
$(document).ready(function(){
  let isMobileDevice = window.matchMedia("only screen and (max-width: 760px)").matches;
  if(isMobileDevice){
    // The viewport is less than 768 pixels wide
    //Conditional script here
  } else{
    //The viewport is greater than 700 pixels wide
    alert("This is not a mobile device.");
  }
});
</script>
```

You can use above script to do show/hide elements depending on the screen size.
