### ISSUE TITLE
How to costumize

### ISSUE THREAD

**Issue by jfoclpf** [centrual/cordova-template-framework7-vue-webpack#64]
Hi, great template, thanks

I already installed and everything went great, but can you tell us simply how to costumize the template? 
Which files? I don't find any relevant file in the folder www/

**Comment by voicecode-bv** [comment]
Use the src folder and read the docs of this repo: 

"www Automatically manages www folder. You don't need to think about www folder. Your target is always src folder."

**Comment by jfoclpf** [comment]
Thanks :) 
Just another question: those .vue files are merely XML or they can take HTML forms for example?

**Comment by voicecode-bv** [comment]
I don't really know what you mean, but if you want to create a form inside a vue component, yes you can. For example you can use Axios to post the form data to your server.

**Comment by jfoclpf** [comment]
Thank you. What I meant is "what is exactly a .vue file and its syntax"? It's merely HTML with another purpose?

**Comment by voicecode-bv** [comment]
Well, a vue file can be used for creating components. Maybe it's better to first find yourself some Vue.js tutorials and read the docs on vuejs.org

**Comment by jfoclpf** [comment]
Thanks a lot! I will look around Vue
It seems really interesting for more user friendly and dynamic JS/HTML applications

**Comment by caiobiodere** [comment]
@jfoclpf you can check the src of this template on https://github.com/framework7io/framework7-vue
