### ISSUE TITLE
cordova run browser doesn't work ubuntu 1.17

### ISSUE THREAD

**Issue by ghost** [centrual/cordova-template-framework7-vue-webpack#65]
Hello,

I have a problem, i cannot lauch my app .
I followed the instruction for the installation , then added platform , then launch cordova run browser but i have this error : 

`Before deploy hook started...
Checking is node modules installed...
Node modules already installed.
Starting webpack build...
Error happened when webpack build: Error: Command failed: "/home/alex/WebstormProjects/allianz/node_modules/.bin/webpack"
/bin/sh: 1: /home/alex/WebstormProjects/allianz/node_modules/.bin/webpack: not found

Webpack build completed to www folder successfully!
Error happened on main chain:
Error: Error happened when webpack build: Error: Command failed: "/home/alex/WebstormProjects/allianz/node_modules/.bin/webpack"
/bin/sh: 1: /home/alex/WebstormProjects/allianz/node_modules/.bin/webpack: not found

    at exec (/home/alex/WebstormProjects/allianz/hooks/hookers.js:187:19)
    at ChildProcess.exithandler (child_process.js:205:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
Error: Error happened when webpack build: Error: Command failed: "/home/alex/WebstormProjects/allianz/node_modules/.bin/webpack"
/bin/sh: 1: /home/alex/WebstormProjects/allianz/node_modules/.bin/webpack: not found
`

before that i also have an error with js beautifier 1.7 so i forced it with 1.6 in my package json

Thanks a lot !

**Comment by dudenk** [comment]
i have some issue.

**Comment by centrual** [comment]
Is webpack path correct? : `/home/alex/WebstormProjects/allianz/node_modules/.bin/webpack`

**Comment by josteph** [comment]
Check whether `webpack` exists inside `node_modules\.bin` folder.

**Comment by caiobiodere** [comment]
I think that's "node_modules\.bin" a good solution for this problem
