### ISSUE TITLE
Live Reload does not work when not using 192.168.[...] local IP address

### ISSUE THREAD

**Issue by jeremymouton** [centrual/cordova-template-framework7-vue-webpack#66]
[hooker.js checks for `192.168.` on line 32](https://github.com/centrual/cordova-template-framework7-vue-webpack/blob/master/template_src/hooks/hookers.js#L32) which causes Live Reload to not work when using a different local IP.

Replacing 

``` js
if (ipInfo.family === 'IPv4' && ipInfo.address.indexOf('192.168.') === 0 && !ipInfo.internal)
              return ipInfo.address
```
with 

``` js
if (ipInfo.family === 'IPv4' && !ipInfo.internal)
              return ipInfo.address

```
fixes the issue.

**Comment by zifengb** [comment]
@jeremymouton Hi, I look up the hooker.js file, the template have been updated. But... I seems meet the issue again, my runtime environment as follows:
 ```
cordova version: 8.0.0
Android version: 8.0.0 Phone -- OnePlus3
node version: 6.11.4
```

Uh... I solve my issue, just I need to link my computer's network.
