### ISSUE TITLE
blank popup screen

### ISSUE THREAD

**Issue by jlugao** [centrual/cordova-template-framework7-vue-webpack#67]
Hey I just installed everything according to instructions. The popup window is blank (and I get stuck in it) I tryed this with and without live reload in browser and android builds. The console doesn't show any errors. When I inspect the element it is indeed blank.

**Comment by josteph** [comment]
Can you provide any screenshot?

**Comment by caiobiodere** [comment]
Hey @jlugao did you follow this documentation?
http://framework7.io/vue

Please check if you are using the correct components
