### ISSUE TITLE
Project not working on Android (< 7.0) browser 

### ISSUE THREAD

**Issue by mrarticuno** [centrual/cordova-template-framework7-vue-webpack#68]
Hi, I just installed a fresh new project but when I try to run at the android native browser (Nox Player android 4.4.4) it returns this error:

![image](https://user-images.githubusercontent.com/3270231/31047264-b50d5c24-a5dd-11e7-9b78-df09d787acc7.png)

Any idea of how I can make the project run in android under version 7.0 ?

**Comment by caiobiodere** [comment]
Just try using the new 2.0.0 version :)
