### ISSUE TITLE
File cleared in static folder

### ISSUE THREAD

**Issue by lcaprini** [centrual/cordova-template-framework7-vue-webpack#69]
In `cordova run browser -- --lr` mode when I change a file in the `src/static` folder with, the template clears all file contents; it appear completely empty.
Can you help me?

**Comment by josteph** [comment]
What change did you make?

**Comment by lcaprini** [comment]
I solved the issue moving 
```javascript
sys.deleteFolderRecursive(targetStaticFolder, true)
sys.copyRecursiveSync(staticFolder, targetStaticFolder)
```
from `makeNonDevServerChanges` to `startWebpackBuild `, before `sys.checkManifestFile()` line.

**Comment by suatatan** [comment]
It also worked for me
