### ISSUE TITLE
How to load images from src/assets/static/images ?

### ISSUE THREAD

**Issue by triasrahman** [centrual/cordova-template-framework7-vue-webpack#7]
I stored the images on `src/assets/static/images` as on template. But how to load it to app? Since there is no images on www folder.

**Comment by centrual** [comment]
Hello @triasrahman 

This problem mostly related with webpack. I can't find any easy way to do it. You can do like:

modify main.vue file with:

``` html
<img :src="images.sample">
```

and

``` javascript
export default {
    data() {
        return {
            images: {
                sample: require('./assets/static/images/sample.jpg')
            }
        }
    }
}
```

or you can use css backgrounds.

**Comment by wakiem** [comment]
Thank you! This worked for me for images in HTML. Is this still the best solution?

But I can't get images from css and from js to work. For example, setting the css background with js:
`$$('#some-element').css('background-image', 'url("./static/images/some-image.png")');`

Do you have an example?

**Comment by centrual** [comment]
Maybe it's not, but I'm using the same as I wrote.

This template using vue.js, so you need to catch HTML elements inside vue. Also, if you looking image path in CSS, you can use `url('../images/image-name.jpg')`

I recommend you to work with vue.js before developing an application with this template.. Because of the usage of vue different than HTML and jquery.

Have a great day!

Note: Bad English and deletion of the reply message made this message bad. It was not my intention to say that the other party did not know.

**Comment by cuduy197** [comment]
How to using image in components ?

**Comment by centrual** [comment]
Hello @wakiem 

I added static folder to template. You can use static folder too for include your static assets now like:

``` html
<img src="static/your_image.png">
```

Have a great day!

**Comment by agfp** [comment]
This works for browser and android debug, but when I compile the app as an adroid release, the images are not loaded.

Any idea on how to solve it?

**Comment by raphmarot** [comment]
Same for me.

It works in dev mode but when compiled images are not loaded (at least for android APK).

Static folder is present in 
`build/intermediates/assets/debug/www `
but not in 
`build/intermediates/assets/release/www`

Any help would be appreciated :-)

**Comment by nmirceac** [comment]
@Vincebe hey - have you ever sorted that out?

Thanks

**Comment by mbaah80** [comment]
i try it but still not working 
<div href="#" class="thumbnail">
      <img src="static/bo.jpg" alt="Book 1">
 </div>

**Comment by agfp** [comment]
I have figured it out. 

`<img :src="$device.desktop ? '/static/image.png' : 'file:./static/image.png'" />`

It will address the image differently on the browser and on mobile, and will load it on both of them.

**Comment by mitkovalkov** [comment]
This work for me:

```
<img :src="image" >

data () {
  return {
    image: require('@/assets/images/pin.svg')
  }
},
```

**Comment by lakshmisap90** [comment]
thanks @mitkovalkov . It worked!

**Comment by cemarta7** [comment]
I dont know if it will be useful for any body but I was able to make the background image work with css with this using the next background url. 

thanks to https://github.com/vuejs/vue-cli/issues/48#issuecomment-312070916

so my css looks like:

`.some-class{
		    background-image: url('~static/images/image.svg');    
}`

**Comment by 0dysseas** [comment]
> This work for me:
> 
> ```
> <img :src="image" >
> 
> data () {
>   return {
>     image: require('@/assets/images/pin.svg')
>   }
> },
> ```
Or this shorthand can also be used (the vue-cli scaffolding project makes use of this):
:src="require('../assets//images/pin.svg')"

**Comment by balakan** [comment]
Thanks @0dysseas.  Worked!

**Comment by CDT** [comment]
> Hello @triasrahman
> 
> This problem mostly related with webpack. I can't find any easy way to do it. You can do like:
> 
> modify main.vue file with:
> 
> ```
> <img :src="images.sample">
> ```
> 
> and
> 
> ```js
> export default {
>     data() {
>         return {
>             images: {
>                 sample: require('./assets/static/images/sample.jpg')
>             }
>         }
>     }
> }
> ```
> 
> or you can use css backgrounds.

Try this simpler syntax(not sure if it works): 

`<img :src="require('./assets/static/images/sample.jpg')">`

**Comment by syntacticsolutions** [comment]
if I do this dynamically it doesn't work.

> > Hello @triasrahman
> > This problem mostly related with webpack. I can't find any easy way to do it. You can do like:
> > modify main.vue file with:
> > ```
> > <img :src="images.sample">
> > ```
> > 
> > 
> > and
> > ```js
> > export default {
> >     data() {
> >         return {
> >             images: {
> >                 sample: require('./assets/static/images/sample.jpg')
> >             }
> >         }
> >     }
> > }
> > ```
> > 
> > 
> > or you can use css backgrounds.
> 
> Try this simpler syntax(not sure if it works):
> 
> `<img :src="require('./assets/static/images/sample.jpg')">`

I tried doing the above example with dynamic data and it didn't work.

**Comment by agfp** [comment]
Define the following mixin on main.js:


```javascript
Vue.mixin({
    methods: {
        getStaticImage(image) {
            return this.$device.desktop ? `/static/${image}` : `file:./static/${image}`;
        }
    }
});
```

Then reference it in the HTML:

```html
<img :src="getStaticImage('sample.jpg')">
```

**Comment by salomon-thomas** [comment]
[object%20Module]:1 GET http://domain.com/my-app/[object%20Module] 404 (Not Found)

      image: require("@/assets/images/souq_chat-logo.jpg")
Why am I getting this error?

**Comment by emforem** [comment]
Here is my solution. Using filter.
```

Vue.filter('img', function (value) {
    return require('@/assets/imagefoler/' + value)
  })

```
and in your .vue you can use
`<img :src="'imagefile.png' | img">`


This should save you from writing require in every :src.

**Comment by proger-coder** [comment]
>                 <img :src="images.sample">
>                 sample: require('./assets/static/images/sample.jpg')

unfortuntately, doesnt work in Vue3+ParcelJS.
Alt text shown instead of img

**Comment by Be-Like** [comment]
> > ```
> >             <img :src="images.sample">
> >             sample: require('./assets/static/images/sample.jpg')
> > ```
> 
> unfortuntately, doesnt work in Vue3+ParcelJS.
> Alt text shown instead of img

@DIMANVAZ Have you found a workaround yet?

**Comment by FahimHassanMollah** [comment]
This works for me 


 data(){
        return {
            logo:require('@/assets/cherry.png')
        }
    }

**Comment by CreativeWarlock** [comment]
Since above methods may be outdated, please find this very helpful stackoverflow post:
https://stackoverflow.com/questions/66419471/vue-3-vite-dynamic-image-src
