### ISSUE TITLE
Use npm device.js instead of git device.js

### ISSUE THREAD

**Issue by levischuckeats** [centrual/cordova-template-framework7-vue-webpack#71]
Change `package.json` to use `    "device.js": "^2.3.0",` instead.

The git reference now pulls something without a device.js to import.

**Comment by antontsvil** [comment]
Thanks very much, this helped solve the following error. It was pretty difficult to find a solution via google so hopefully this comment will lead people here :

`ERROR in ./webpack/dev_helpers/CordovaDeviceRouter.js
Module not found: Error: Can't resolve 'device.js' in '/.../webpack/dev_helpers'
 @ ./webpack/dev_helpers/CordovaDeviceRouter.js 1:17-37
 @ multi ./src/main.js ./webpack/dev_helpers/CordovaDeviceRouter.js`

Additionally, you will want to edit CordovaDeviceRouter.js from the following format
**original :** deviceJs.desktop()
**correct :** deviceJs.device.desktop

the end of the file should look like this :
`if (deviceJs.device.desktop)
	bodyPrepend("browser")
else if (deviceJs.device.android)
	bodyPrepend("android")
else if (deviceJs.device.ios)
	bodyPrepend("ios")
else
	alert("Platform not found!")`

**Comment by yelban** [comment]
It's not work if just change deviceJs.desktop()

You need to change device.js to current-device on both `./package.json` and `./webpack/dev_helpers/CordovaDeviceRouter.js`

`./package.json`
\- "device.js": "git+https://github.com/matthewhudson/device.js.git",
\+ "current-device": "^0.6.0",

`webpack/dev_helpers/CordovaDeviceRouter.js`
\- const deviceJs = require('device.js').default
\+ const deviceJs = require('current-device').default

[PR request](https://github.com/centrual/cordova-template-framework7-vue-webpack/pull/72/commits/7960e8fb0ebd802a8b6d98615f1c4a8e8982261c)
