### ISSUE TITLE
cordova serve command does nothing

### ISSUE THREAD

**Issue by tomrlh** [centrual/cordova-template-framework7-vue-webpack#78]
`cordova serve` command does nothing, not even a error message.. I already added a browser platform, am I forgetting something :confused: ?

**Comment by josteph** [comment]
Please use `cordova run [platform] -- --lr` command instead.

OR

`cordova build [platform]` then `cordova run [platform]`.

Take note that the `-- --lr` will make the webpack automatically inject corresponding platform `cordova.js`
