### ISSUE TITLE
How to add Plugins to Project without Live Reload?

### ISSUE THREAD

**Issue by josteph** [centrual/cordova-template-framework7-vue-webpack#79]
Hello, I am trying to add some cordova plugins such as [Facebook Login](https://github.com/jeduan/cordova-plugin-facebook4) and [Social Sharing](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin). But unfortunately, I found that those plugins are not injected when not using live reload command, for example:
`cordova build android` therefore currently my apk build doesnt recognize any plugin even when installed.

I also found that in `www/` folder, there is no `cordova.js` and `cordova_plugins.js` files. But I actually found those cordova files in `platforms/android/assets/www` folder.

Do I need to reference the plugin manually in `index.html` ? For example, `<script src="/plugins/www/facebook-native.js"></script>`

Any help is appreciated, this is my current `index.html` output generated in `platforms/android/assets/www`when using cordova build command:
```
<!DOCTYPE html>
<html>
<head>

<meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no,minimal-ui">
<meta name=apple-mobile-web-app-capable content=yes>
<title>My App</title>
<link href=styles.css rel=stylesheet>

</head>

<body>

<div id=app></div>

<script src=f141c146cafb6e042456.main.js></script>
<script src=cordova.js></script>

</body>

</html>
```

**Comment by andrewleech** [comment]
Did you solve this? 
I've got a similar issue...

**Comment by caiobiodere** [comment]
@andrewleech did you check using the new 2.0.0 version and updating your npm version?
