### ISSUE TITLE
statusbar-overlay not working in IOS

### ISSUE THREAD

**Issue by silasmatheus** [centrual/cordova-template-framework7-vue-webpack#8]
statusbar-overlay should be inserted in body context, but it is not possible in this model (body > div id="app" > body). How should we does?

![image](https://cloud.githubusercontent.com/assets/1700605/22792717/d00d8d52-eed4-11e6-90c6-9c289e55badf.png)

**Comment by centrual** [comment]
You asked same question in framework7-vue issues. You can see the answer there: https://github.com/nolimits4web/Framework7-Vue/issues/95

Have a great day!
