### ISSUE TITLE
When new npm lib is added, webpack gives an error

### ISSUE THREAD

**Issue by tomrlh** [centrual/cordova-template-framework7-vue-webpack#80]
I'm trying to use [google maps components](https://github.com/xkjyeah/vue-google-maps), but when I add the lib in main.js > `npm install` > `cordova run android --device` it gives the error:

`Error: Error happened when webpack build: Error: Command failed: "/project_path/node_modules/.bin/webpack"`

Basically in every modification I make to main.js it gives this error, and can't run in android or browser anymore, am I forgetting something? :worried:

**Comment by tomrlh** [comment]
Other question, to develop I'm not able to develop in vue server? like `npm run dev` to have the live-reload, because cordova live-reload is not working as I want, I have to make te updates and recompile the project. `npm install` but `npm run dev` don't.

**Comment by centrual** [comment]
I didn't assigned anything to `npm run` because there are multiple options you can run. `cordova run android -- --lr` command runs `vue-server` for you.

If you want to see real error, you need to run webpack command directly in your main directory like:

``` bash
> cd "C:/Users/.../MyMainProjectFolder/"
> .\node_modules\.bin\webpack
```
