### ISSUE TITLE
"deviceready" event

### ISSUE THREAD

**Issue by vvarda** [centrual/cordova-template-framework7-vue-webpack#81]
How can I handle "deviceready" event in this template?
Or it has been involved somehow to internal Vue components lifecycle (created, mounted etc.) ?

**Comment by vvarda** [comment]
Guys?

**Comment by josteph** [comment]
I usually do it within mounted. And then you can just:

```
if (window.cordova) {
    document.addEventListener('backbutton', () => {
       // do something here
    }, false)
}
```
