### ISSUE TITLE
How change into production ?

### ISSUE THREAD

**Issue by edoofx** [centrual/cordova-template-framework7-vue-webpack#82]
im working with this template , and works well when develop ( at browser mode ) , but when im type
-add platform android
then
-cordova run android --device
-APK running at my device, but show whitescreen only.
same with cordova build android --release bla bla bla bla , then install APK on my device, run , and same , whitescreen only ..

**Comment by caiobiodere** [comment]
Please check again using the new 2.0.0 version :)
