### ISSUE TITLE
could this template add Microsoft Cordova-Simulate support?

### ISSUE THREAD

**Issue by kiler398** [centrual/cordova-template-framework7-vue-webpack#83]
Cordova-Simulate is  Microsoft's plugin can Simulates Apache Cordova application in the browser.
https://github.com/Microsoft/cordova-simulate
if add this plugin,we can debug some native api function in the browser.

**Comment by caiobiodere** [comment]
hey @kiler398, could you help us about how to import this application into cordova-template-framework7-vue-webpack template?

**Comment by kiler398** [comment]
I find a solution to use  Microsoft Cordova-Simulate 
if we install a cordova-tools plugin in vscode,we can use Microsoft Cordova-Simulate  for your template
https://marketplace.visualstudio.com/items?itemName=vsmobile.cordova-tools

**Comment by caiobiodere** [comment]
Great idea @kiler398 I made your tip in README file :)
