### ISSUE TITLE
Live reload can't connect on android device

### ISSUE THREAD

**Issue by ghost** [centrual/cordova-template-framework7-vue-webpack#84]
Hi,

i created a new project with the last template and installed platforms for browser and android.

Then i tried: cordova run android -- --lr to use the live reload function on my android device. Everything worked as expected

![image](https://user-images.githubusercontent.com/27993481/35210401-5133651c-ff52-11e7-8980-5d00ae188a08.png)

but it can't connect to 192.168.56.1:8081. In the browser everything works fine, also 127.0.0.1:8081

Any settings if have forgotten?

**Comment by caiobiodere** [comment]
Did you try using the simulator? please :)

Everything is working using simulator here

<img width="1065" alt="screen shot 2018-01-22 at 11 59 06 am" src="https://user-images.githubusercontent.com/1935649/35224317-becce1f2-ff6b-11e7-8337-9d10eea6c35c.png">

**Comment by saltyeyes** [comment]
Could you please update the readme to mention that live reload on a physical device isn't supported? Would have saved me a bunch of time. :c

**Comment by caiobiodere** [comment]
@saltyeyes yes i will do it

**Comment by centrual** [comment]
Live reload normally works in same network. Is your phone connected to same router-wifi? Also is your phone connected with cable too?

If all yes than:
1) If app displays white screen after launch, it's probably about cordova platform files not loaded. Please check loaded cordova platform files from `chrome://inspect`
2) If app renders content but when you changed something, changes not affecting an app or app screen transforms to white screen, it is related with live reload.

**Comment by caiobiodere** [comment]
@SgtPepper27 Did you check using centrual tips?
