### ISSUE TITLE
Current Framework7 Vue documentation is for Framework7 v1.x and for Framework7 Vue v0.x and not compatible with Framework7 v2

### ISSUE THREAD

**Issue by vvarda** [centrual/cordova-template-framework7-vue-webpack#85]
1. When will documentation be updated?
2. What was changed basically for Vue + F7 connection (routing, components etc.)?
3. How can I use last template's version now?

F7 is awesome. Thx.

**Comment by caiobiodere** [comment]
Hey mate, When I realized to change our version I found three new articles about F7 v2 you can check there:

https://blog.framework7.io/framework7-v2-beta-41f983d6e89d
https://blog.framework7.io/migration-to-framework7-v2-eb6dc38ede3b
https://blog.framework7.io/mastering-v2-router-958ea2dbd24f

**Comment by caiobiodere** [comment]
About framework7-vue v2 you can check references to study there:

https://github.com/framework7io/framework7-vue/tree/master/kitchen-sink/src/pages

**Comment by vvarda** [comment]
@caiobiodere yep, updated "kitchen-sink" example is all that I need. Thx.

**Comment by caiobiodere** [comment]
@vvarda Awesome 👍
