### ISSUE TITLE
How to remove cordova?

### ISSUE THREAD

**Issue by JCKodel** [centrual/cordova-template-framework7-vue-webpack#86]
This template is better than recommended F7 Vue template because hot-load actually works (this replaces contents on the fly, the other one reloads the entire app, even on a simple css change), and it appears to be more active than the other.

The problem is that I'm making a simple website, not a cordova app =\ I guess leaving cordova will lead to some problems and overhead.

Anyway... It is possible to make this template (or a fork of it) to work without cordova?

**Comment by caiobiodere** [comment]
Hi @JCKodel Nice to meet you :)

I think you can use this option if you want to keep using VueJS with Webpack: https://github.com/vuejs/vue-cli

**Comment by JCKodel** [comment]
Thank you! Worked perfectly!

For those who are working with https://github.com/framework7io/Framework7-Vue-Webpack-Template, applying this solution requires almost no change at all (and hot reloading will work without reloading the page).

> Bom saber que tem brazuca ativo na comunidade. ;-)
