### ISSUE TITLE
cannot create cordova app

### ISSUE THREAD

**Issue by snzmnrdn** [centrual/cordova-template-framework7-vue-webpack#87]
```
(node:3197) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): App id contains a reserved word, or is not a valid identifier.
(node:3197) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by theMangledBadger** [comment]
Quick one, when you're running the create cordova app commands: 

`cordova create <project_create_dir> [com.example.projectname] [ProjectClassName] --template cordova-template-framework7-vue-webpack`

`phonegap create <project_create_dir> [com.example.projectname] [ProjectClassName] --template cordova-template-framework7-vue-webpack`

Ensure you don't have any illegal characters within the `[ProjectClassName]` or `[com.example.projectname]`, this on caught me out initially. 

For example:
`cordova create my-project-directory [com.directory.project.my] [MyProjectDirectory] --template cordova-template-framework7-vue-webpack`

Should get you up and running.

**Comment by mwargan** [comment]
Also experiencing this issue on a fresh install with `cordova create cordova data-center [com.example.data] [DataCenter] --template cordova-template-framework7-vue-webpack`... with Cordova v8.

Edit: silly me, I had to remove the brackets :P
