### ISSUE TITLE
Android (<= 6.0) white screen after start

### ISSUE THREAD

**Issue by vvarda** [centrual/cordova-template-framework7-vue-webpack#89]
cordova-cli: 7.1.0 || 8.0.0

"cordova-android": "^6.4.0",
"cordova-plugin-whitelist": "^1.3.3",
"font-awesome": "^4.7.0",
"framework7": "^2.0.6",
"framework7-icons": "^0.9.0",
"framework7-vue": "^2.0.0",
"loglevel": "^1.4.1",
"vue": "^2.5.13"

I try to start empty project via that template. But it works only on Android 7.0.0+ versions.

![1517402113009](https://user-images.githubusercontent.com/4321362/35623372-076aeeac-0694-11e8-9ff5-042743b3e53d.jpg)

Android 6.0.0 and less (emulator and devices) shows only white screen after start.

![1517401516034](https://user-images.githubusercontent.com/4321362/35623069-c471899a-0692-11e8-95f7-c7c900b062b4.jpg)

Upd. 1:
Also, I've tried to add [cordova-splashscreen-plugin](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/) -- it works. But after splash screen I get white screen.

Upd. 2:
```
<preference name="android-minSdkVersion" value="16" />
<preference name="android-targetSdkVersion" value="21" />
```
Also did nothing.

**Comment by victoryhb** [comment]
This is probably due to the lack of support for es2015 features in older android webviews. Transpiling to es5 using babel in webpack should solve the problem.

**Comment by vvarda** [comment]
@victoryhb yep, I've understood, but can't just transpile all **node_modules** packages -- Webpack crashes.

Maybe someone knows, which package should we transpile to es5?

**Comment by vvarda** [comment]
@caiobiodere I've tried to debug app in Android Studio (API less 23) and stuck on error:
`"Uncaught SyntaxError: Use of const in strict mode.", source: file:///android_asset/www/de6e2d3a966ab131f3c6.main.js`

which follows to:
`const defaultDiacriticsRemovalap = [...]`

It means that old WebView on Android doesn't support **ES6**: including **const** definition

Any ideas?

**Comment by caiobiodere** [comment]
I added babel and rules to transpile our project using ECMAScript, but I don't know how can we fix that for all node_modules packages.

**Comment by vvarda** [comment]
@caiobiodere the problem is in framework7|framework7-vue|template7|dom7 packages.

There is an [issue](https://github.com/framework7io/framework7/issues/2156), but it was accidentally closed.

So, for temporary solution I changed webpack config like that:
```
{
  test: /\.js$/,
  exclude: /node_modules\/(?!(framework7|framework7-vue|template7|dom7)\/).*/,
  use: {
    loader: 'babel-loader',
    options: {
      presets: [ 'env' ],
      plugins: [ 'transform-runtime' ]
    }
  }
}
```

**Comment by caiobiodere** [comment]
@vvarda awesome idea for this moment, I already did this if you can let me know any new changes
