### ISSUE TITLE
how to android back button??

### ISSUE THREAD

**Issue by poptong** [centrual/cordova-template-framework7-vue-webpack#90]
main.vue

    methods: {
        handleBackButton () {
            if (this.$f7router.history.length > 1) {
                 return this.$f7router.back();
             }
    },
    created () {
        document.addEventListener('deviceready', () => {
            document.addEventListener('backbutton', this.handleBackButton);
        });
    }

backbutton not works...
Cannot read property 'history' of undefined
Cannot read property 'back' of undefined

**Comment by caiobiodere** [comment]
You can use the back property:

`<f7-list-button title="Cancel" back></f7-list-button>`
