### ISSUE TITLE
The exported APK can't open

### ISSUE THREAD

**Issue by Acroipeol** [centrual/cordova-template-framework7-vue-webpack#91]
It says "ERR cannot find the www/index" when i open the exported apk. please help

**Comment by caiobiodere** [comment]
Hey @Acroipeol everything is working here using this command: `cordova build android`, can you use my last release? https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/releases/tag/2.0.2

Node version: 8.9.4
Npm version: 5.6.0
Cordova version: 7.1.0
Android API version: +23

<img width="1235" alt="screen shot 2018-02-13 at 7 12 12 pm" src="https://user-images.githubusercontent.com/1935649/36173968-e3567b72-10f1-11e8-8fe0-9fadd43fab61.png">
