### ISSUE TITLE
Your download installs F7 V1

### ISSUE THREAD

**Issue by tribalboy3000** [centrual/cordova-template-framework7-vue-webpack#92]
I used this:

cordova create <project_create_dir> [com.example.projectname] [ProjectClassName] --template cordova-template-framework7-vue-webpack

if you check installed code main.js the code is for f7 v1, this was caught by the author of F7.

**Comment by caiobiodere** [comment]
Hey, @tribalboy3000 can you check using this release?
https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/releases/tag/2.0.3

About framework7 version we are using F7 v2, I used from this reference:
https://github.com/framework7io/framework7-template-vue-webpack/blob/master/src/main.js

**Comment by daniel-centore** [comment]
Using the following yields F7 v1 for me as well:

    cordova create <project_create_dir> [com.example.projectname] [ProjectClassName] --template cordova-template-framework7-vue-webpack

Installing with the following gives me F7 v2:

    cordova create <project_create_dir> [com.example.projectname] [ProjectClassName] --template https://github.com/caiobiodere/cordova-template-framework7-vue-webpack

Perhaps the documentation should be updated to make sure folks are getting the right version? Or is there something you need to do to make sure the template gets updated in Cordova's db?

**Comment by caiobiodere** [comment]
@daniel-centore great idea! hey @tribalboy3000 you just need to use this command to create your project 👍 

`cordova create <project_create_dir> [com.example.projectname] [ProjectClassName] --template https://github.com/caiobiodere/cordova-template-framework7-vue-webpack
`

**Comment by tribalboy3000** [comment]
Ok thanks!
