### ISSUE TITLE
iPhoneX not showing up fullscreen

### ISSUE THREAD

**Issue by daniel-centore** [centrual/cordova-template-framework7-vue-webpack#93]
When I try to use this framework with an iPhoneX, it doesn't extend all the way to the top and bottom as I would expect.

<img src="https://user-images.githubusercontent.com/569864/36601417-12b99366-1883-11e8-9ce2-956b5e495e35.png" width="400"  />

**Comment by daniel-centore** [comment]
I was able to resolve this issue with the help of [this article](https://blog.phonegap.com/displaying-a-phonegap-app-correctly-on-the-iphone-x-c4a85664c493), by adding a blank 2372x2372 image at `res/screen/ios/Default@2x~universal~anyany.png` and then including the following line within `<platform name="ios">` in `config.xml`:

    <splash src="res/screen/ios/Default@2x~universal~anyany.png" />

<img width="259" alt="screen shot 2018-02-23 at 11 48 56 am" src="https://user-images.githubusercontent.com/569864/36605722-8db5d802-188f-11e8-849b-c7f25246543b.png">

**Comment by caiobiodere** [comment]
hey @daniel-centore thanks for your help I did these changes you can check on: https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/releases/tag/2.0.4
