### ISSUE TITLE
Router in vuex

### ISSUE THREAD

**Issue by vvarda** [centrual/cordova-template-framework7-vue-webpack#96]
How can I get router in Vuex module to navigate in my app?

I need to navigate somewhere in Vuex modules mutations or actions via dependence from data.

In simply Vue project we have vue-router Router instance, so it could be used just like a:
```
import router from './router
router.push
```

But what about framework7-vue and current template, where we are only able to call `this.$f7.views[0].router` in components ?

**Comment by caiobiodere** [comment]
Hmm I really don't know how can we do it, because we are using framework7 structure to navigate between pages following framework7 router. I will ask but for a moment you could use events and data.

**Comment by vvarda** [comment]
@caiobiodere thx. 

It's really awful case now. I have to use computed properties to watch when Vuex state value changes and then control Router depending on it.

**Comment by caiobiodere** [comment]
Good job 👍
