### ISSUE TITLE
Add Template, add platform , run and error at device

### ISSUE THREAD

**Issue by edoofx** [centrual/cordova-template-framework7-vue-webpack#98]
1. cordova create testcreate com.testcreate testcreate --template https://github.com/caiobiodere/cordova-template-framework7-vue-webpack
2. cd testcreate
3. npm i
4. remove line 46 at webpack.config
5. cordova platform add android
6. cordova run android --device

**and voila. white screen at device , but work on browser**

and at console say : Uncaught SyntaxError: Use of future reserved word in strict mode 

i check , error at **let theme = 'auto';** , **and i change into 'md'** . same. whitescreen

**Comment by caiobiodere** [comment]
hey @edoofx why are you removing line 46? I created that to run on android devices that are using API 23 :)

I did the same things you made and everything is running here. Could you check your npm, node and cordova versions?

Npm version: 5.6.0
Node version: 8.9.4
Cordova version: 8.0.0
cordova-android version: 7.0.0

<img width="1679" alt="screen shot 2018-03-06 at 12 20 27 pm" src="https://user-images.githubusercontent.com/1935649/37040535-e0381066-2138-11e8-81e9-6566478d372b.png">

**Comment by edoofx** [comment]
hey @caiobiodere .. why removing line 46 ? because i cant run.. like at _tab issues_ ..
Npm version: 5.6.0
Node version: 8.9.4
Cordova version: 6.5.0
cordova-android version: 6.1.2

now i know the problem..

if cordova@7.0.0 . this is can run .

thanks for the answer..

**Comment by caiobiodere** [comment]
Awesome, good job 👍
