### ISSUE TITLE
How to update my template cloned before?

### ISSUE THREAD

**Issue by yulin724** [centrual/cordova-template-framework7-vue-webpack#99]
I very like this project, and use it in my project.

How to update my template cloned before?

**Comment by caiobiodere** [comment]
I think this is a good start for you @yulin724 

* [Migration to Framework7 v2](https://blog.framework7.io/migration-to-framework7-v2-eb6dc38ede3b)
* [Mastering router Framework7 v2](https://blog.framework7.io/mastering-v2-router-958ea2dbd24f)

**Comment by caiobiodere** [comment]
hey @yulin724 how was it?

**Comment by caiobiodere** [comment]
Please let me know if you need something more about this task
